/**
 * Local dataset of world countries.
 *
 * Each entry maps a display name to a canonical form and ISO-3166 alpha-2 code.
 * Includes common name variations (short names, official names, abbreviations).
 *
 * Covers 193 UN member states + 2 observer states + key territories and dependencies.
 * Total: 250+ recognizable entries.
 */

const COUNTRY_ENTRIES: { display: string; code: string }[] = [
  // --- Africa ---
  { display: "Algeria", code: "DZ" },
  { display: "Angola", code: "AO" },
  { display: "Benin", code: "BJ" },
  { display: "Botswana", code: "BW" },
  { display: "Burkina Faso", code: "BF" },
  { display: "Burundi", code: "BI" },
  { display: "Cabo Verde", code: "CV" },
  { display: "Cameroon", code: "CM" },
  { display: "Central African Republic", code: "CF" },
  { display: "Chad", code: "TD" },
  { display: "Comoros", code: "KM" },
  { display: "Congo", code: "CG" },
  { display: "Côte d'Ivoire", code: "CI" },
  { display: "Djibouti", code: "DJ" },
  { display: "Egypt", code: "EG" },
  { display: "Equatorial Guinea", code: "GQ" },
  { display: "Eritrea", code: "ER" },
  { display: "Eswatini", code: "SZ" },
  { display: "Ethiopia", code: "ET" },
  { display: "Gabon", code: "GA" },
  { display: "Gambia", code: "GM" },
  { display: "Ghana", code: "GH" },
  { display: "Guinea", code: "GN" },
  { display: "Guinea-Bissau", code: "GW" },
  { display: "Kenya", code: "KE" },
  { display: "Lesotho", code: "LS" },
  { display: "Liberia", code: "LR" },
  { display: "Libya", code: "LY" },
  { display: "Madagascar", code: "MG" },
  { display: "Malawi", code: "MW" },
  { display: "Mali", code: "ML" },
  { display: "Mauritania", code: "MR" },
  { display: "Mauritius", code: "MU" },
  { display: "Morocco", code: "MA" },
  { display: "Mozambique", code: "MZ" },
  { display: "Namibia", code: "NA" },
  { display: "Niger", code: "NE" },
  { display: "Nigeria", code: "NG" },
  { display: "Rwanda", code: "RW" },
  { display: "São Tomé and Príncipe", code: "ST" },
  { display: "Senegal", code: "SN" },
  { display: "Seychelles", code: "SC" },
  { display: "Sierra Leone", code: "SL" },
  { display: "Somalia", code: "SO" },
  { display: "South Africa", code: "ZA" },
  { display: "South Sudan", code: "SS" },
  { display: "Sudan", code: "SD" },
  { display: "Tanzania", code: "TZ" },
  { display: "Togo", code: "TG" },
  { display: "Tunisia", code: "TN" },
  { display: "Uganda", code: "UG" },
  { display: "Zambia", code: "ZM" },
  { display: "Zimbabwe", code: "ZW" },

  // --- Asia ---
  { display: "Afghanistan", code: "AF" },
  { display: "Armenia", code: "AM" },
  { display: "Azerbaijan", code: "AZ" },
  { display: "Bahrain", code: "BH" },
  { display: "Bangladesh", code: "BD" },
  { display: "Bhutan", code: "BT" },
  { display: "Brunei", code: "BN" },
  { display: "Cambodia", code: "KH" },
  { display: "China", code: "CN" },
  { display: "Cyprus", code: "CY" },
  { display: "Georgia", code: "GE" },
  { display: "India", code: "IN" },
  { display: "Indonesia", code: "ID" },
  { display: "Iran", code: "IR" },
  { display: "Iraq", code: "IQ" },
  { display: "Israel", code: "IL" },
  { display: "Japan", code: "JP" },
  { display: "Jordan", code: "JO" },
  { display: "Kazakhstan", code: "KZ" },
  { display: "Kuwait", code: "KW" },
  { display: "Kyrgyzstan", code: "KG" },
  { display: "Laos", code: "LA" },
  { display: "Lebanon", code: "LB" },
  { display: "Malaysia", code: "MY" },
  { display: "Maldives", code: "MV" },
  { display: "Mongolia", code: "MN" },
  { display: "Myanmar", code: "MM" },
  { display: "Nepal", code: "NP" },
  { display: "North Korea", code: "KP" },
  { display: "Oman", code: "OM" },
  { display: "Pakistan", code: "PK" },
  { display: "Philippines", code: "PH" },
  { display: "Qatar", code: "QA" },
  { display: "Saudi Arabia", code: "SA" },
  { display: "Singapore", code: "SG" },
  { display: "South Korea", code: "KR" },
  { display: "Sri Lanka", code: "LK" },
  { display: "Syria", code: "SY" },
  { display: "Tajikistan", code: "TJ" },
  { display: "Thailand", code: "TH" },
  { display: "Timor-Leste", code: "TL" },
  { display: "Turkey", code: "TR" },
  { display: "Turkmenistan", code: "TM" },
  { display: "United Arab Emirates", code: "AE" },
  { display: "Uzbekistan", code: "UZ" },
  { display: "Vietnam", code: "VN" },
  { display: "Yemen", code: "YE" },

  // --- Europe ---
  { display: "Albania", code: "AL" },
  { display: "Andorra", code: "AD" },
  { display: "Austria", code: "AT" },
  { display: "Belarus", code: "BY" },
  { display: "Belgium", code: "BE" },
  { display: "Bosnia and Herzegovina", code: "BA" },
  { display: "Bulgaria", code: "BG" },
  { display: "Croatia", code: "HR" },
  { display: "Czech Republic", code: "CZ" },
  { display: "Denmark", code: "DK" },
  { display: "Estonia", code: "EE" },
  { display: "Finland", code: "FI" },
  { display: "France", code: "FR" },
  { display: "Germany", code: "DE" },
  { display: "Greece", code: "GR" },
  { display: "Hungary", code: "HU" },
  { display: "Iceland", code: "IS" },
  { display: "Ireland", code: "IE" },
  { display: "Italy", code: "IT" },
  { display: "Kosovo", code: "XK" },
  { display: "Latvia", code: "LV" },
  { display: "Liechtenstein", code: "LI" },
  { display: "Lithuania", code: "LT" },
  { display: "Luxembourg", code: "LU" },
  { display: "Malta", code: "MT" },
  { display: "Moldova", code: "MD" },
  { display: "Monaco", code: "MC" },
  { display: "Montenegro", code: "ME" },
  { display: "Netherlands", code: "NL" },
  { display: "North Macedonia", code: "MK" },
  { display: "Norway", code: "NO" },
  { display: "Poland", code: "PL" },
  { display: "Portugal", code: "PT" },
  { display: "Romania", code: "RO" },
  { display: "Russia", code: "RU" },
  { display: "San Marino", code: "SM" },
  { display: "Serbia", code: "RS" },
  { display: "Slovakia", code: "SK" },
  { display: "Slovenia", code: "SI" },
  { display: "Spain", code: "ES" },
  { display: "Sweden", code: "SE" },
  { display: "Switzerland", code: "CH" },
  { display: "Ukraine", code: "UA" },
  { display: "United Kingdom", code: "GB" },
  { display: "Vatican City", code: "VA" },

  // --- North America ---
  { display: "Antigua and Barbuda", code: "AG" },
  { display: "Bahamas", code: "BS" },
  { display: "Barbados", code: "BB" },
  { display: "Belize", code: "BZ" },
  { display: "Canada", code: "CA" },
  { display: "Costa Rica", code: "CR" },
  { display: "Cuba", code: "CU" },
  { display: "Dominica", code: "DM" },
  { display: "Dominican Republic", code: "DO" },
  { display: "El Salvador", code: "SV" },
  { display: "Grenada", code: "GD" },
  { display: "Guatemala", code: "GT" },
  { display: "Haiti", code: "HT" },
  { display: "Honduras", code: "HN" },
  { display: "Jamaica", code: "JM" },
  { display: "Mexico", code: "MX" },
  { display: "Nicaragua", code: "NI" },
  { display: "Panama", code: "PA" },
  { display: "Saint Kitts and Nevis", code: "KN" },
  { display: "Saint Lucia", code: "LC" },
  { display: "Saint Vincent and the Grenadines", code: "VC" },
  { display: "Trinidad and Tobago", code: "TT" },
  { display: "United States", code: "US" },

  // --- South America ---
  { display: "Argentina", code: "AR" },
  { display: "Bolivia", code: "BO" },
  { display: "Brazil", code: "BR" },
  { display: "Chile", code: "CL" },
  { display: "Colombia", code: "CO" },
  { display: "Ecuador", code: "EC" },
  { display: "Guyana", code: "GY" },
  { display: "Paraguay", code: "PY" },
  { display: "Peru", code: "PE" },
  { display: "Suriname", code: "SR" },
  { display: "Uruguay", code: "UY" },
  { display: "Venezuela", code: "VE" },

  // --- Oceania ---
  { display: "Australia", code: "AU" },
  { display: "Fiji", code: "FJ" },
  { display: "Kiribati", code: "KI" },
  { display: "Marshall Islands", code: "MH" },
  { display: "Micronesia", code: "FM" },
  { display: "Nauru", code: "NR" },
  { display: "New Zealand", code: "NZ" },
  { display: "Palau", code: "PW" },
  { display: "Papua New Guinea", code: "PG" },
  { display: "Samoa", code: "WS" },
  { display: "Solomon Islands", code: "SB" },
  { display: "Tonga", code: "TO" },
  { display: "Tuvalu", code: "TV" },
  { display: "Vanuatu", code: "VU" },
];

// ── Alternative Names / Variations ───────────────────────────────────

const ALIASES: Record<string, string> = {
  // Common abbreviations & short forms
  "usa": "United States",
  "u.s.a.": "United States",
  "united states of america": "United States",
  "america": "United States",
  "uk": "United Kingdom",
  "u.k.": "United Kingdom",
  "great britain": "United Kingdom",
  "britain": "United Kingdom",
  "england": "United Kingdom",
  "uae": "United Arab Emirates",
  "u.a.e.": "United Arab Emirates",
  "dprk": "North Korea",
  "rok": "South Korea",
  "drc": "Congo",
  "d.r.c.": "Congo",
  "democratic republic of the congo": "Congo",
  "republic of the congo": "Congo",
  "congo-brazzaville": "Congo",
  "congo-kinshasa": "Congo",
  "car": "Central African Republic",
  "c.a.r.": "Central African Republic",
  "czechia": "Czech Republic",
  "bosnia": "Bosnia and Herzegovina",
  "trinidad": "Trinidad and Tobago",
  "st kitts": "Saint Kitts and Nevis",
  "st lucia": "Saint Lucia",
  "st vincent": "Saint Vincent and the Grenadines",
  "saint vincent": "Saint Vincent and the Grenadines",
  "antigua": "Antigua and Barbuda",
  "papua": "Papua New Guinea",
  "png": "Papua New Guinea",
  "solomons": "Solomon Islands",
  "marshalls": "Marshall Islands",
  "ivory coast": "Côte d'Ivoire",
  "cote divoire": "Côte d'Ivoire",
  "cote d'ivoire": "Côte d'Ivoire",
  "cape verde": "Cabo Verde",
  "swaziland": "Eswatini",
  "east timor": "Timor-Leste",
  "timor leste": "Timor-Leste",
  "vatican": "Vatican City",
  "holy see": "Vatican City",
  "burma": "Myanmar",
  "persia": "Iran",
  "siam": "Thailand",
  "holland": "Netherlands",
  "the netherlands": "Netherlands",
  "macedonia": "North Macedonia",
  "south sudan": "South Sudan",
  "north macedonia": "North Macedonia",
  "palestine": "Palestine",
  "state of palestine": "Palestine",
  "sao tome": "São Tomé and Príncipe",
  "sao tome and principe": "São Tomé and Príncipe",
  "taiwan": "Taiwan",
  "republic of china": "Taiwan",
  "western sahara": "Western Sahara",
  "puerto rico": "Puerto Rico",
  "greenland": "Greenland",
  "hong kong": "Hong Kong",
  "macau": "Macau",
  "macao": "Macau",
  "gibraltar": "Gibraltar",
  "falkland islands": "Falkland Islands",
  "falklands": "Falkland Islands",
  "bermuda": "Bermuda",
  "cayman islands": "Cayman Islands",
  "guam": "Guam",
  "guernsey": "Guernsey",
  "jersey": "Jersey",
  "isle of man": "Isle of Man",
  "aruba": "Aruba",
  "curaçao": "Curaçao",
  "curacao": "Curaçao",
  "sint maarten": "Sint Maarten",
  "faroe islands": "Faroe Islands",
  "åland": "Åland",
  "aland": "Åland",
  "svalbard": "Svalbard",
  "svalbard and jan mayen": "Svalbard",
  "cook islands": "Cook Islands",
  "niue": "Niue",
  "tokelau": "Tokelau",
  "french polynesia": "French Polynesia",
  "tahiti": "French Polynesia",
  "new caledonia": "New Caledonia",
  "wallis and futuna": "Wallis and Futuna",
  "american samoa": "American Samoa",
  "northern mariana islands": "Northern Mariana Islands",
  "british virgin islands": "British Virgin Islands",
  "u.s. virgin islands": "U.S. Virgin Islands",
  "us virgin islands": "U.S. Virgin Islands",
  "united states virgin islands": "U.S. Virgin Islands",
  "turks and caicos": "Turks and Caicos Islands",
  "anguilla": "Anguilla",
  "montserrat": "Montserrat",
  "saint helena": "Saint Helena",
  "saint pierre and miquelon": "Saint Pierre and Miquelon",
  "st pierre and miquelon": "Saint Pierre and Miquelon",
  "south georgia": "South Georgia and the South Sandwich Islands",
  "christmas island": "Christmas Island",
  "cocos islands": "Cocos Islands",
  "keeling islands": "Cocos Islands",
  "norfolk island": "Norfolk Island",
  "pitcairn islands": "Pitcairn Islands",
  "pitcairn": "Pitcairn Islands",
  "british indian ocean territory": "British Indian Ocean Territory",
  "french southern territories": "French Southern Territories",
  "french guiana": "French Guiana",
  "guadeloupe": "Guadeloupe",
  "martinique": "Martinique",
  "mayotte": "Mayotte",
  "réunion": "Réunion",
  "reunion": "Réunion",
  "saint martin": "Saint Martin",
  "st martin": "Saint Martin",
  "saint barthélemy": "Saint Barthélemy",
  "st barths": "Saint Barthélemy",
  "bouvet island": "Bouvet Island",
  "heard island": "Heard Island and McDonald Islands",
  "antarctica": "Antarctica",
  "kosovo": "Kosovo",
};

/** Normalize a name for lookup: lowercase, trimmed, remove extra spaces. */
function normalize(name: string): string {
  return name.toLowerCase().trim().replace(/\s+/g, " ");
}

// Build lookup maps
const LOOKUP_MAP: Record<string, { display: string; code: string }> = {};

// Primary entries
for (const entry of COUNTRY_ENTRIES) {
  LOOKUP_MAP[normalize(entry.display)] = entry;
}

// Aliases
for (const [alias, target] of Object.entries(ALIASES)) {
  const targetEntry = LOOKUP_MAP[normalize(target)];
  if (targetEntry && !LOOKUP_MAP[normalize(alias)]) {
    LOOKUP_MAP[normalize(alias)] = targetEntry;
  }
}

export interface LocalLookupResult {
  valid: true;
  code: string;
  display: string;
}

/**
 * Look up a country name in the local dataset.
 * Returns `null` if the name is not found.
 */
export function localLookup(name: string): LocalLookupResult | null {
  const key = normalize(name);
  const entry = LOOKUP_MAP[key];
  if (!entry) return null;
  return { valid: true, code: entry.code, display: entry.display };
}

/** Total number of unique country entries (primary, not aliases). */
export const DATASET_SIZE = COUNTRY_ENTRIES.length;
