/**
 * Local food dataset for the Name 100 Food challenge.
 *
 * Checked FIRST before any Wikidata API call. Covers common foods across
 * categories — fruits, vegetables, meats, seafood, grains, dairy, baked
 * goods, desserts, snacks, drinks, dishes, and condiments.
 *
 * Each entry maps a canonical display name; common synonyms are handled
 * via the ALIASES map below (e.g. "aubergine" → "Eggplant").
 */

const FOOD_ENTRIES: { display: string }[] = [
  // ─── Fruits ─────────────────────────────────────────────────────────
  { display: "Apple" },
  { display: "Banana" },
  { display: "Orange" },
  { display: "Strawberry" },
  { display: "Grape" },
  { display: "Watermelon" },
  { display: "Pineapple" },
  { display: "Mango" },
  { display: "Peach" },
  { display: "Pear" },
  { display: "Cherry" },
  { display: "Blueberry" },
  { display: "Raspberry" },
  { display: "Blackberry" },
  { display: "Lemon" },
  { display: "Lime" },
  { display: "Coconut" },
  { display: "Avocado" },
  { display: "Kiwi" },
  { display: "Papaya" },
  { display: "Plum" },
  { display: "Fig" },
  { display: "Date" },
  { display: "Melon" },
  { display: "Cantaloupe" },
  { display: "Honeydew" },
  { display: "Nectarine" },
  { display: "Apricot" },
  { display: "Pomegranate" },
  { display: "Grapefruit" },
  { display: "Cranberry" },
  { display: "Gooseberry" },
  { display: "Lychee" },
  { display: "Passion fruit" },
  { display: "Guava" },
  { display: "Persimmon" },
  { display: "Starfruit" },
  { display: "Dragon fruit" },
  { display: "Tangerine" },
  { display: "Mandarin" },
  { display: "Olive" },

  // ─── Vegetables ─────────────────────────────────────────────────────
  { display: "Carrot" },
  { display: "Potato" },
  { display: "Tomato" },
  { display: "Onion" },
  { display: "Garlic" },
  { display: "Broccoli" },
  { display: "Cauliflower" },
  { display: "Cabbage" },
  { display: "Lettuce" },
  { display: "Spinach" },
  { display: "Kale" },
  { display: "Cucumber" },
  { display: "Bell pepper" },
  { display: "Chili pepper" },
  { display: "Eggplant" },
  { display: "Zucchini" },
  { display: "Pumpkin" },
  { display: "Butternut squash" },
  { display: "Acorn squash" },
  { display: "Corn" },
  { display: "Pea" },
  { display: "Green bean" },
  { display: "Asparagus" },
  { display: "Celery" },
  { display: "Radish" },
  { display: "Beet" },
  { display: "Mushroom" },
  { display: "Sweet potato" },
  { display: "Artichoke" },
  { display: "Leek" },
  { display: "Scallion" },
  { display: "Brussels sprout" },
  { display: "Okra" },
  { display: "Parsnip" },
  { display: "Turnip" },
  { display: "Watercress" },
  { display: "Swiss chard" },
  { display: "Daikon" },
  { display: "Jicama" },
  { display: "Cilantro" },
  { display: "Basil" },
  { display: "Parsley" },
  { display: "Mint" },
  { display: "Oregano" },
  { display: "Thyme" },
  { display: "Rosemary" },
  { display: "Sage" },
  { display: "Dill" },
  { display: "Ginger" },
  { display: "Turmeric" },

  // ─── Meats ──────────────────────────────────────────────────────────
  { display: "Beef" },
  { display: "Pork" },
  { display: "Chicken" },
  { display: "Turkey" },
  { display: "Lamb" },
  { display: "Bacon" },
  { display: "Ham" },
  { display: "Sausage" },
  { display: "Salami" },
  { display: "Pepperoni" },
  { display: "Duck" },
  { display: "Goose" },
  { display: "Veal" },
  { display: "Venison" },
  { display: "Prosciutto" },
  { display: "Jerky" },
  { display: "Steak" },
  { display: "Ribs" },
  { display: "Meatloaf" },

  // ─── Seafood ────────────────────────────────────────────────────────
  { display: "Salmon" },
  { display: "Tuna" },
  { display: "Shrimp" },
  { display: "Crab" },
  { display: "Lobster" },
  { display: "Oyster" },
  { display: "Clam" },
  { display: "Cod" },
  { display: "Trout" },
  { display: "Sardine" },
  { display: "Anchovy" },
  { display: "Squid" },
  { display: "Octopus" },
  { display: "Scallop" },
  { display: "Mussel" },
  { display: "Tilapia" },
  { display: "Catfish" },
  { display: "Halibut" },
  { display: "Swordfish" },
  { display: "Mahi-mahi" },
  { display: "Eel" },
  { display: "Caviar" },
  { display: "Prawn" },
  { display: "Bass" },

  // ─── Grains & Staples ───────────────────────────────────────────────
  { display: "Rice" },
  { display: "Bread" },
  { display: "Pasta" },
  { display: "Noodle" },
  { display: "Oats" },
  { display: "Wheat" },
  { display: "Barley" },
  { display: "Quinoa" },
  { display: "Flour" },
  { display: "Cereal" },
  { display: "Bagel" },
  { display: "Croissant" },
  { display: "Cornbread" },
  { display: "Rice cake" },
  { display: "Oatmeal" },
  { display: "Grits" },
  { display: "Couscous" },
  { display: "Polenta" },
  { display: "Tortilla" },
  { display: "Pita" },
  { display: "Baguette" },
  { display: "Sourdough" },
  { display: "Rye bread" },
  { display: "Lentil" },
  { display: "Chickpea" },
  { display: "Bean" },
  { display: "Paneer" },

  // ─── Dairy ──────────────────────────────────────────────────────────
  { display: "Milk" },
  { display: "Cheese" },
  { display: "Butter" },
  { display: "Yogurt" },
  { display: "Cream" },
  { display: "Ice cream" },
  { display: "Cheddar" },
  { display: "Mozzarella" },
  { display: "Parmesan" },
  { display: "Cottage cheese" },
  { display: "Sour cream" },
  { display: "Ghee" },
  { display: "Cream cheese" },
  { display: "Swiss cheese" },
  { display: "Blue cheese" },
  { display: "Brie" },
  { display: "Feta" },
  { display: "Ricotta" },
  { display: "Goat cheese" },
  { display: "Egg" },

  // ─── Baked Goods & Desserts ─────────────────────────────────────────
  { display: "Cake" },
  { display: "Cookie" },
  { display: "Pie" },
  { display: "Apple pie" },
  { display: "Donut" },
  { display: "Muffin" },
  { display: "Brownie" },
  { display: "Pancake" },
  { display: "Waffle" },
  { display: "Cheesecake" },
  { display: "Cupcake" },
  { display: "Cinnamon roll" },
  { display: "Tart" },
  { display: "Scone" },
  { display: "Biscuit" },
  { display: "Bread pudding" },
  { display: "Creme brulee" },
  { display: "Flan" },
  { display: "Pudding" },
  { display: "Gelato" },
  { display: "Sorbet" },
  { display: "Fudge" },
  { display: "Caramel" },
  { display: "Candy" },
  { display: "Chocolate" },
  { display: "Chocolate cake" },
  { display: "Macaron" },
  { display: "Cannoli" },
  { display: "Eclair" },

  // ─── Snacks ─────────────────────────────────────────────────────────
  { display: "Chips" },
  { display: "Popcorn" },
  { display: "Pretzel" },
  { display: "Crackers" },
  { display: "Almonds" },
  { display: "Peanuts" },
  { display: "Cashews" },
  { display: "Pistachios" },
  { display: "Walnuts" },
  { display: "Pecans" },
  { display: "Hazelnuts" },
  { display: "Granola" },
  { display: "Nachos" },
  { display: "Trail mix" },
  { display: "French fries" },
  { display: "Tortilla chips" },
  { display: "Onion rings" },
  { display: "Sunflower seeds" },
  { display: "Sesame seeds" },
  { display: "Chia seeds" },

  // ─── Drinks ─────────────────────────────────────────────────────────
  { display: "Coffee" },
  { display: "Iced coffee" },
  { display: "Tea" },
  { display: "Green tea" },
  { display: "Black tea" },
  { display: "Juice" },
  { display: "Orange juice" },
  { display: "Apple juice" },
  { display: "Grape juice" },
  { display: "Soda" },
  { display: "Cola" },
  { display: "Lemonade" },
  { display: "Smoothie" },
  { display: "Beer" },
  { display: "Wine" },
  { display: "Red wine" },
  { display: "White wine" },
  { display: "Hot chocolate" },
  { display: "Milkshake" },
  { display: "Water" },
  { display: "Iced tea" },
  { display: "Espresso" },
  { display: "Latte" },
  { display: "Cappuccino" },
  { display: "Champagne" },
  { display: "Whiskey" },
  { display: "Vodka" },
  { display: "Rum" },
  { display: "Cocktail" },

  // ─── Dishes & Meals ─────────────────────────────────────────────────
  { display: "Pizza" },
  { display: "Sushi" },
  { display: "Burger" },
  { display: "Sandwich" },
  { display: "Taco" },
  { display: "Burrito" },
  { display: "Ramen" },
  { display: "Fried rice" },
  { display: "Salad" },
  { display: "Soup" },
  { display: "Curry" },
  { display: "Dumpling" },
  { display: "Hot dog" },
  { display: "Kebab" },
  { display: "Lasagna" },
  { display: "Risotto" },
  { display: "Paella" },
  { display: "Sashimi" },
  { display: "Quesadilla" },
  { display: "Chili" },
  { display: "Stew" },
  { display: "Chowder" },
  { display: "Goulash" },
  { display: "Stir fry" },
  { display: "Falafel" },
  { display: "Hummus" },
  { display: "Guacamole" },
  { display: "Poke" },
  { display: "Meatball" },
  { display: "Spring roll" },
  { display: "Egg roll" },
  { display: "Dim sum" },
  { display: "Biryani" },
  { display: "Pad thai" },
  { display: "Pho" },
  { display: "Shawarma" },
  { display: "Gyro" },
  { display: "Enchilada" },
  { display: "Fajita" },
  { display: "Empanada" },
  { display: "Samosa" },
  { display: "Pierogi" },
  { display: "Gnocchi" },
  { display: "Ravioli" },
  { display: "Spaghetti" },
  { display: "Macaroni" },
  { display: "Poutine" },
  { display: "Haggis" },
  { display: "Tagine" },
  { display: "Feijoada" },
  { display: "Sauerbraten" },
  { display: "Borscht" },
  { display: "Churro" },
  { display: "Ceviche" },
  { display: "Bulgogi" },
  { display: "Pavlova" },
  { display: "Gyoza" },
  { display: "Bao" },
  { display: "Arepa" },
  { display: "Croquette" },
  { display: "Omelette" },
  { display: "Quiche" },
  { display: "Ratatouille" },
  { display: "Gazpacho" },
  { display: "Minestrone" },

  // ─── Condiments & Sauces ────────────────────────────────────────────
  { display: "Ketchup" },
  { display: "Mustard" },
  { display: "Mayonnaise" },
  { display: "Salsa" },
  { display: "Soy sauce" },
  { display: "Vinegar" },
  { display: "Olive oil" },
  { display: "Maple syrup" },
  { display: "Honey" },
  { display: "Jam" },
  { display: "Peanut butter" },
  { display: "Ranch" },
  { display: "Barbecue sauce" },
  { display: "Hot sauce" },
  { display: "Pesto" },
  { display: "Marmalade" },
  { display: "Tzatziki" },
  { display: "Salt" },
  { display: "Sugar" },
  { display: "Pepper" },
  { display: "Cinnamon" },
  { display: "Vanilla" },
  { display: "Miso" },
  { display: "Sesame oil" },
];

// ── Alternative Names / Variations ───────────────────────────────────

const ALIASES: Record<string, string> = {
  // Fruits
  "strawberries": "Strawberry",
  "grapes": "Grape",
  "blueberries": "Blueberry",
  "raspberries": "Raspberry",
  "blackberries": "Blackberry",
  "clementine": "Mandarin",
  // Vegetables
  "aubergine": "Eggplant",
  "courgette": "Zucchini",
  "zucchini squash": "Zucchini",
  "capsicum": "Bell pepper",
  "sweet pepper": "Bell pepper",
  "green onion": "Scallion",
  "spring onion": "Scallion",
  "scallions": "Scallion",
  "coriander": "Cilantro",
  "maize": "Corn",
  "sweet corn": "Corn",
  "yams": "Sweet potato",
  "yam": "Sweet potato",
  "coriander leaves": "Cilantro",
  "fresh coriander": "Cilantro",
  "ginger": "Ginger",
  "turmeric": "Turmeric",
  "olives": "Olive",
  "lentils": "Lentil",
  "chickpeas": "Chickpea",
  "garbanzo": "Chickpea",
  "garbanzo beans": "Chickpea",
  "beans": "Bean",
  "kidney beans": "Bean",
  "black beans": "Bean",
  "pinto beans": "Bean",
  "green beans": "Green bean",
  "sunflower seed": "Sunflower seeds",
  "sesame seed": "Sesame seeds",
  "chia seed": "Chia seeds",
  "tomatoes": "Tomato",
  "potatoes": "Potato",
  "onions": "Onion",
  "carrots": "Carrot",
  "mushrooms": "Mushroom",
  "peas": "Pea",
  "string bean": "Green bean",
  "string beans": "Green bean",
  "snap pea": "Pea",
  "brussels sprouts": "Brussels sprout",
  "squash": "Butternut squash",
  // Meats
  "ground beef": "Beef",
  "minced beef": "Beef",
  "chicken breast": "Chicken",
  "pork chop": "Pork",
  "pork belly": "Pork",
  "hot dogs": "Hot dog",
  "sausages": "Sausage",
  "beef jerky": "Jerky",
  "turkey bacon": "Turkey",
  // Seafood
  "prawns": "Prawn",
  "shrimps": "Shrimp",
  "king prawn": "Prawn",
  "clams": "Clam",
  "oysters": "Oyster",
  "mussels": "Mussel",
  "scallops": "Scallop",
  "squids": "Squid",
  "octopus": "Octopus",
  "bass fish": "Bass",
  "sea bass": "Bass",
  "tuna fish": "Tuna",
  "salmon fish": "Salmon",
  "crab meat": "Crab",
  // Grains & Staples
  "noodles": "Noodle",
  "rice noodles": "Noodle",
  "whole wheat bread": "Bread",
  "baguettes": "Baguette",
  "tortillas": "Tortilla",
  "pita bread": "Pita",
  "flatbread": "Pita",
  "baked potato": "Potato",
  "mashed potato": "Potato",
  "fries": "French fries",
  "chips": "Chips",
  "crisps": "Chips",
  "potato chips": "Chips",
  "frenchfries": "French fries",
  // Dairy
  "yoghurt": "Yogurt",
  "yoghourt": "Yogurt",
  "mozzarella cheese": "Mozzarella",
  "parmesan cheese": "Parmesan",
  "cheddar cheese": "Cheddar",
  "feta cheese": "Feta",
  "brie cheese": "Brie",
  "cream cheese": "Cream cheese",
  "eggs": "Egg",
  "egg whites": "Egg",
  // Baked Goods & Desserts
  "doughnut": "Donut",
  "donuts": "Donut",
  "doughnuts": "Donut",
  "cookies": "Cookie",
  "biscuits": "Biscuit",
  "pancakes": "Pancake",
  "waffles": "Waffle",
  "brownies": "Brownie",
  "muffins": "Muffin",
  "cupcakes": "Cupcake",
  "cup cake": "Cupcake",
  "icecream": "Ice cream",
  "ice creams": "Ice cream",
  "gelato": "Gelato",
  "sorbets": "Sorbet",
  "candy": "Candy",
  "sweets": "Candy",
  "candies": "Candy",
  "lollipop": "Candy",
  "chocolates": "Chocolate",
  "chocolate bar": "Chocolate",
  "pie": "Pie",
  "cheesecakes": "Cheesecake",
  "puddings": "Pudding",
  "flan": "Flan",
  "caramel": "Caramel",
  // Snacks
  "popcorns": "Popcorn",
  "pretzels": "Pretzel",
  "almond": "Almonds",
  "peanut": "Peanuts",
  "groundnut": "Peanuts",
  "groundnuts": "Peanuts",
  "cashew": "Cashews",
  "pistachio": "Pistachios",
  "walnut": "Walnuts",
  "pecan": "Pecans",
  "hazelnut": "Hazelnuts",
  "granola bar": "Granola",
  "nachos": "Nachos",
  "onion ring": "Onion rings",
  "onion rings": "Onion rings",
  // Drinks
  "coke": "Cola",
  "coca cola": "Cola",
  "coca-cola": "Cola",
  "soft drink": "Soda",
  "soft drinks": "Soda",
  "soda pop": "Soda",
  "fizzy drink": "Soda",
  "fruit juice": "Juice",
  "coffee latte": "Latte",
  "latte": "Latte",
  "cappuccino": "Cappuccino",
  "espresso": "Espresso",
  "iced tea": "Iced tea",
  "hot cocoa": "Hot chocolate",
  "cocoa": "Hot chocolate",
  "milkshakes": "Milkshake",
  "smoothies": "Smoothie",
  "lemonades": "Lemonade",
  "beers": "Beer",
  "whisky": "Whiskey",
  "milk shake": "Milkshake",
  // Dishes & Meals
  "pizzas": "Pizza",
  "hamburger": "Burger",
  "hamburgers": "Burger",
  "cheeseburger": "Burger",
  "burgers": "Burger",
  "sandwiches": "Sandwich",
  "grilled cheese": "Sandwich",
  "tacos": "Taco",
  "burritos": "Burrito",
  "ramens": "Ramen",
  "sushi rolls": "Sushi",
  "dumplings": "Dumpling",
  "spring rolls": "Spring roll",
  "egg rolls": "Egg roll",
  "curries": "Curry",
  "stews": "Stew",
  "chowders": "Chowder",
  "kebabs": "Kebab",
  "kebab": "Kebab",
  "lasagne": "Lasagna",
  "spaghettis": "Spaghetti",
  "mac and cheese": "Macaroni",
  "macaroni and cheese": "Macaroni",
  "ravioli": "Ravioli",
  "gnocchi": "Gnocchi",
  "samosa": "Samosa",
  "empanadas": "Empanada",
  "enchiladas": "Enchilada",
  "fajitas": "Fajita",
  "quesadillas": "Quesadilla",
  "shwarma": "Shawarma",
  "gyros": "Gyro",
  "falafels": "Falafel",
  "hummus": "Hummus",
  "guacamoles": "Guacamole",
  "pokes": "Poke",
  "biryani": "Biryani",
  "padthai": "Pad thai",
  "pho": "Pho",
  "meatballs": "Meatball",
  "chili con carne": "Chili",
  "chilli": "Chili",
  "poutine": "Poutine",
  "borscht": "Borscht",
  "tagine": "Tagine",
  // Condiments & Sauces
  "catsup": "Ketchup",
  "tomato sauce": "Ketchup",
  "mustards": "Mustard",
  "mayo": "Mayonnaise",
  "salsas": "Salsa",
  "soy sauce": "Soy sauce",
  "vinagar": "Vinegar",
  "vinegars": "Vinegar",
  "olive oil": "Olive oil",
  "maple syrup": "Maple syrup",
  "honeys": "Honey",
  "jams": "Jam",
  "jelly": "Jam",
  "peanutbutter": "Peanut butter",
  "ranch dressing": "Ranch",
  "bbq sauce": "Barbecue sauce",
  "barbeque sauce": "Barbecue sauce",
  "hot sauces": "Hot sauce",
  "sriracha": "Hot sauce",
  "pesto": "Pesto",
  "marmalades": "Marmalade",
  "miso": "Miso",
  "sesame oil": "Sesame oil",
  "table salt": "Salt",
  "salt": "Salt",
  "sugars": "Sugar",
  "white sugar": "Sugar",
  "black pepper": "Pepper",
  "peppercorns": "Pepper",
  "cinnamon": "Cinnamon",
  "vanilla extract": "Vanilla",
};

/** Normalize a name for lookup: lowercase, trimmed, remove extra spaces. */
function normalize(name: string): string {
  return name.toLowerCase().trim().replace(/\s+/g, " ");
}

// Build lookup maps
const LOOKUP_MAP: Record<string, { display: string }> = {};

// Primary entries
for (const entry of FOOD_ENTRIES) {
  LOOKUP_MAP[normalize(entry.display)] = entry;
}

// Aliases
for (const [alias, target] of Object.entries(ALIASES)) {
  const targetEntry = LOOKUP_MAP[normalize(target)];
  if (targetEntry && !LOOKUP_MAP[normalize(alias)]) {
    LOOKUP_MAP[normalize(alias)] = targetEntry;
  }
}

export interface LocalLookupResult {
  valid: true;
  display: string;
}

/**
 * Look up a food name in the local dataset.
 * Returns `null` if the name is not found.
 */
export function localLookup(name: string): LocalLookupResult | null {
  const key = normalize(name);
  const entry = LOOKUP_MAP[key];
  if (!entry) return null;
  return { valid: true, display: entry.display };
}

/** Total number of unique food entries (primary, not aliases). */
export const DATASET_SIZE = FOOD_ENTRIES.length;
