/**
 * Local dataset of Pokémon names.
 *
 * Covers all 9 generations — 300+ recognizable Pokémon.
 * Each entry: display name → canonical form. Aliases handle common variations.
 */

const POKEMON_ENTRIES: string[] = [
  // ── Generation 1 (Kanto) ──────────────────────────────────────────
  "Bulbasaur", "Ivysaur", "Venusaur",
  "Charmander", "Charmeleon", "Charizard",
  "Squirtle", "Wartortle", "Blastoise",
  "Caterpie", "Metapod", "Butterfree",
  "Weedle", "Kakuna", "Beedrill",
  "Pidgey", "Pidgeotto", "Pidgeot",
  "Rattata", "Raticate",
  "Spearow", "Fearow",
  "Ekans", "Arbok",
  "Pikachu", "Raichu",
  "Sandshrew", "Sandslash",
  "Nidoran♀", "Nidorina", "Nidoqueen",
  "Nidoran♂", "Nidorino", "Nidoking",
  "Clefairy", "Clefable",
  "Vulpix", "Ninetales",
  "Jigglypuff", "Wigglytuff",
  "Zubat", "Golbat",
  "Oddish", "Gloom", "Vileplume",
  "Paras", "Parasect",
  "Venonat", "Venomoth",
  "Diglett", "Dugtrio",
  "Meowth", "Persian",
  "Psyduck", "Golduck",
  "Mankey", "Primeape",
  "Growlithe", "Arcanine",
  "Poliwag", "Poliwhirl", "Poliwrath",
  "Abra", "Kadabra", "Alakazam",
  "Machop", "Machoke", "Machamp",
  "Bellsprout", "Weepinbell", "Victreebel",
  "Tentacool", "Tentacruel",
  "Geodude", "Graveler", "Golem",
  "Ponyta", "Rapidash",
  "Slowpoke", "Slowbro",
  "Magnemite", "Magneton",
  "Farfetch'd",
  "Doduo", "Dodrio",
  "Seel", "Dewgong",
  "Grimer", "Muk",
  "Shellder", "Cloyster",
  "Gastly", "Haunter", "Gengar",
  "Onix",
  "Drowzee", "Hypno",
  "Krabby", "Kingler",
  "Voltorb", "Electrode",
  "Exeggcute", "Exeggutor",
  "Cubone", "Marowak",
  "Hitmonlee", "Hitmonchan",
  "Lickitung",
  "Koffing", "Weezing",
  "Rhyhorn", "Rhydon",
  "Chansey",
  "Tangela",
  "Kangaskhan",
  "Horsea", "Seadra",
  "Goldeen", "Seaking",
  "Staryu", "Starmie",
  "Mr. Mime",
  "Scyther",
  "Jynx",
  "Electabuzz",
  "Magmar",
  "Pinsir",
  "Tauros",
  "Magikarp", "Gyarados",
  "Lapras",
  "Ditto",
  "Eevee", "Vaporeon", "Jolteon", "Flareon",
  "Porygon",
  "Omanyte", "Omastar",
  "Kabuto", "Kabutops",
  "Aerodactyl",
  "Snorlax",
  "Articuno", "Zapdos", "Moltres",
  "Dratini", "Dragonair", "Dragonite",
  "Mewtwo", "Mew",

  // ── Generation 2 (Johto) ──────────────────────────────────────────
  "Chikorita", "Bayleef", "Meganium",
  "Cyndaquil", "Quilava", "Typhlosion",
  "Totodile", "Croconaw", "Feraligatr",
  "Sentret", "Furret",
  "Hoothoot", "Noctowl",
  "Ledyba", "Ledian",
  "Spinarak", "Ariados",
  "Crobat",
  "Chinchou", "Lanturn",
  "Pichu",
  "Cleffa",
  "Igglybuff",
  "Togepi", "Togetic",
  "Natu", "Xatu",
  "Mareep", "Flaaffy", "Ampharos",
  "Bellossom",
  "Marill", "Azumarill",
  "Sudowoodo",
  "Politoed",
  "Hoppip", "Skiploom", "Jumpluff",
  "Aipom",
  "Sunkern", "Sunflora",
  "Yanma",
  "Wooper", "Quagsire",
  "Espeon", "Umbreon",
  "Murkrow",
  "Slowking",
  "Misdreavus",
  "Unown",
  "Wobbuffet",
  "Girafarig",
  "Pineco", "Forretress",
  "Dunsparce",
  "Gligar",
  "Steelix",
  "Snubbull", "Granbull",
  "Qwilfish",
  "Scizor",
  "Shuckle",
  "Heracross",
  "Sneasel",
  "Teddiursa", "Ursaring",
  "Slugma", "Magcargo",
  "Swinub", "Piloswine",
  "Corsola",
  "Remoraid", "Octillery",
  "Delibird",
  "Mantine",
  "Skarmory",
  "Houndour", "Houndoom",
  "Kingdra",
  "Phanpy", "Donphan",
  "Porygon2",
  "Stantler",
  "Smeargle",
  "Tyrogue", "Hitmontop",
  "Smoochum",
  "Elekid",
  "Magby",
  "Miltank",
  "Blissey",
  "Raikou", "Entei", "Suicune",
  "Larvitar", "Pupitar", "Tyranitar",
  "Lugia", "Ho-Oh", "Celebi",

  // ── Generation 3 (Hoenn) ──────────────────────────────────────────
  "Treecko", "Grovyle", "Sceptile",
  "Torchic", "Combusken", "Blaziken",
  "Mudkip", "Marshtomp", "Swampert",
  "Poochyena", "Mightyena",
  "Zigzagoon", "Linoone",
  "Wurmple", "Silcoon", "Beautifly", "Cascoon", "Dustox",
  "Lotad", "Lombre", "Ludicolo",
  "Seedot", "Nuzleaf", "Shiftry",
  "Taillow", "Swellow",
  "Wingull", "Pelipper",
  "Ralts", "Kirlia", "Gardevoir",
  "Surskit", "Masquerain",
  "Shroomish", "Breloom",
  "Slakoth", "Vigoroth", "Slaking",
  "Nincada", "Ninjask", "Shedinja",
  "Whismur", "Loudred", "Exploud",
  "Makuhita", "Hariyama",
  "Azurill",
  "Nosepass",
  "Skitty", "Delcatty",
  "Sableye",
  "Mawile",
  "Aron", "Lairon", "Aggron",
  "Meditite", "Medicham",
  "Electrike", "Manectric",
  "Plusle", "Minun",
  "Volbeat", "Illumise",
  "Roselia",
  "Gulpin", "Swalot",
  "Carvanha", "Sharpedo",
  "Wailmer", "Wailord",
  "Numel", "Camerupt",
  "Torkoal",
  "Spoink", "Grumpig",
  "Spinda",
  "Trapinch", "Vibrava", "Flygon",
  "Cacnea", "Cacturne",
  "Swablu", "Altaria",
  "Zangoose", "Seviper",
  "Lunatone", "Solrock",
  "Barboach", "Whiscash",
  "Corphish", "Crawdaunt",
  "Baltoy", "Claydol",
  "Lileep", "Cradily",
  "Anorith", "Armaldo",
  "Feebas", "Milotic",
  "Castform",
  "Kecleon",
  "Shuppet", "Banette",
  "Duskull", "Dusclops",
  "Tropius",
  "Chimecho",
  "Absol",
  "Wynaut",
  "Snorunt", "Glalie",
  "Spheal", "Sealeo", "Walrein",
  "Clamperl", "Huntail", "Gorebyss",
  "Relicanth",
  "Luvdisc",
  "Bagon", "Shelgon", "Salamence",
  "Beldum", "Metang", "Metagross",
  "Regirock", "Regice", "Registeel",
  "Latias", "Latios",
  "Kyogre", "Groudon", "Rayquaza",
  "Jirachi", "Deoxys",

  // ── Generation 4 (Sinnoh) ─────────────────────────────────────────
  "Turtwig", "Grotle", "Torterra",
  "Chimchar", "Monferno", "Infernape",
  "Piplup", "Prinplup", "Empoleon",
  "Starly", "Staravia", "Staraptor",
  "Bidoof", "Bibarel",
  "Kricketot", "Kricketune",
  "Shinx", "Luxio", "Luxray",
  "Budew", "Roserade",
  "Cranidos", "Rampardos",
  "Shieldon", "Bastiodon",
  "Burmy", "Wormadam", "Mothim",
  "Combee", "Vespiquen",
  "Pachirisu",
  "Buizel", "Floatzel",
  "Cherubi", "Cherrim",
  "Shellos", "Gastrodon",
  "Ambipom",
  "Drifloon", "Drifblim",
  "Buneary", "Lopunny",
  "Mismagius",
  "Honchkrow",
  "Glameow", "Purugly",
  "Chingling",
  "Stunky", "Skuntank",
  "Bronzor", "Bronzong",
  "Bonsly",
  "Mime Jr.",
  "Happiny",
  "Chatot",
  "Spiritomb",
  "Gible", "Gabite", "Garchomp",
  "Munchlax",
  "Riolu", "Lucario",
  "Hippopotas", "Hippowdon",
  "Skorupi", "Drapion",
  "Croagunk", "Toxicroak",
  "Carnivine",
  "Finneon", "Lumineon",
  "Mantyke",
  "Snover", "Abomasnow",
  "Weavile",
  "Magnezone",
  "Lickilicky",
  "Rhyperior",
  "Tangrowth",
  "Electivire",
  "Magmortar",
  "Togekiss",
  "Yanmega",
  "Leafeon", "Glaceon",
  "Gliscor",
  "Mamoswine",
  "Porygon-Z",
  "Gallade",
  "Probopass",
  "Dusknoir",
  "Froslass",
  "Rotom",
  "Uxie", "Mesprit", "Azelf",
  "Dialga", "Palkia", "Heatran",
  "Regigigas",
  "Giratina",
  "Cresselia",
  "Phione", "Manaphy",
  "Darkrai",
  "Shaymin", "Arceus",

  // ── Generation 5 (Unova) ──────────────────────────────────────────
  "Victini",
  "Snivy", "Servine", "Serperior",
  "Tepig", "Pignite", "Emboar",
  "Oshawott", "Dewott", "Samurott",
  "Patrat", "Watchog",
  "Lillipup", "Herdier", "Stoutland",
  "Purrloin", "Liepard",
  "Pansage", "Simisage",
  "Pansear", "Simisear",
  "Panpour", "Simipour",
  "Munna", "Musharna",
  "Pidove", "Tranquill", "Unfezant",
  "Blitzle", "Zebstrika",
  "Roggenrola", "Boldore", "Gigalith",
  "Woobat", "Swoobat",
  "Drilbur", "Excadrill",
  "Audino",
  "Timburr", "Gurdurr", "Conkeldurr",
  "Tympole", "Palpitoad", "Seismitoad",
  "Throh", "Sawk",
  "Sewaddle", "Swadloon", "Leavanny",
  "Venipede", "Whirlipede", "Scolipede",
  "Cottonee", "Whimsicott",
  "Petilil", "Lilligant",
  "Basculin",
  "Sandile", "Krokorok", "Krookodile",
  "Darumaka", "Darmanitan",
  "Maractus",
  "Dwebble", "Crustle",
  "Scraggy", "Scrafty",
  "Sigilyph",
  "Yamask", "Cofagrigus",
  "Tirtouga", "Carracosta",
  "Archen", "Archeops",
  "Trubbish", "Garbodor",
  "Zorua", "Zoroark",
  "Minccino", "Cinccino",
  "Gothita", "Gothorita", "Gothitelle",
  "Solosis", "Duosion", "Reuniclus",
  "Ducklett", "Swanna",
  "Vanillite", "Vanillish", "Vanilluxe",
  "Deerling", "Sawsbuck",
  "Emolga",
  "Karrablast", "Escavalier",
  "Foongus", "Amoonguss",
  "Frillish", "Jellicent",
  "Alomomola",
  "Joltik", "Galvantula",
  "Ferroseed", "Ferrothorn",
  "Klink", "Klang", "Klinklang",
  "Tynamo", "Eelektrik", "Eelektross",
  "Elgyem", "Beheeyem",
  "Litwick", "Lampent", "Chandelure",
  "Axew", "Fraxure", "Haxorus",
  "Cubchoo", "Beartic",
  "Cryogonal",
  "Shelmet", "Accelgor",
  "Stunfisk",
  "Mienfoo", "Mienshao",
  "Druddigon",
  "Golett", "Golurk",
  "Pawniard", "Bisharp",
  "Bouffalant",
  "Rufflet", "Braviary",
  "Vullaby", "Mandibuzz",
  "Heatmor", "Durant",
  "Deino", "Zweilous", "Hydreigon",
  "Larvesta", "Volcarona",
  "Cobalion", "Terrakion", "Virizion",
  "Tornadus", "Thundurus",
  "Reshiram", "Zekrom",
  "Landorus", "Kyurem",
  "Keldeo", "Meloetta", "Genesect",

  // ── Generation 6 (Kalos) ──────────────────────────────────────────
  "Chespin", "Quilladin", "Chesnaught",
  "Fennekin", "Braixen", "Delphox",
  "Froakie", "Frogadier", "Greninja",
  "Bunnelby", "Diggersby",
  "Fletchling", "Fletchinder", "Talonflame",
  "Scatterbug", "Spewpa", "Vivillon",
  "Litleo", "Pyroar",
  "Flabébé", "Floette", "Florges",
  "Skiddo", "Gogoat",
  "Pancham", "Pangoro",
  "Furfrou",
  "Espurr", "Meowstic",
  "Honedge", "Doublade", "Aegislash",
  "Spritzee", "Aromatisse",
  "Swirlix", "Slurpuff",
  "Inkay", "Malamar",
  "Binacle", "Barbaracle",
  "Skrelp", "Dragalge",
  "Clauncher", "Clawitzer",
  "Helioptile", "Heliolisk",
  "Tyrunt", "Tyrantrum",
  "Amaura", "Aurorus",
  "Sylveon",
  "Hawlucha",
  "Dedenne",
  "Carbink",
  "Goomy", "Sliggoo", "Goodra",
  "Klefki",
  "Phantump", "Trevenant",
  "Pumpkaboo", "Gourgeist",
  "Bergmite", "Avalugg",
  "Noibat", "Noivern",
  "Xerneas", "Yveltal",
  "Zygarde", "Diancie",
  "Hoopa", "Volcanion",

  // ── Generation 7 (Alola) ──────────────────────────────────────────
  "Rowlet", "Dartrix", "Decidueye",
  "Litten", "Torracat", "Incineroar",
  "Popplio", "Brionne", "Primarina",
  "Pikipek", "Trumbeak", "Toucannon",
  "Yungoos", "Gumshoos",
  "Grubbin", "Charjabug", "Vikavolt",
  "Crabrawler", "Crabominable",
  "Oricorio",
  "Cutiefly", "Ribombee",
  "Rockruff", "Lycanroc",
  "Wishiwashi",
  "Mareanie", "Toxapex",
  "Mudbray", "Mudsdale",
  "Dewpider", "Araquanid",
  "Fomantis", "Lurantis",
  "Morelull", "Shiinotic",
  "Salandit", "Salazzle",
  "Stufful", "Bewear",
  "Bounsweet", "Steenee", "Tsareena",
  "Comfey",
  "Oranguru",
  "Passimian",
  "Wimpod", "Golisopod",
  "Sandygast", "Palossand",
  "Pyukumuku",
  "Type: Null", "Silvally",
  "Minior",
  "Komala",
  "Turtonator",
  "Togedemaru",
  "Mimikyu",
  "Bruxish",
  "Drampa",
  "Dhelmise",
  "Jangmo-o", "Hakamo-o", "Kommo-o",
  "Tapu Koko", "Tapu Lele", "Tapu Bulu", "Tapu Fini",
  "Cosmog", "Cosmoem",
  "Solgaleo", "Lunala",
  "Nihilego", "Buzzwole", "Pheromosa", "Xurkitree",
  "Celesteela", "Kartana", "Guzzlord",
  "Necrozma", "Magearna",
  "Marshadow",
  "Poipole", "Naganadel",
  "Stakataka", "Blacephalon",
  "Zeraora", "Meltan", "Melmetal",

  // ── Generation 8 (Galar) ──────────────────────────────────────────
  "Grookey", "Thwackey", "Rillaboom",
  "Scorbunny", "Raboot", "Cinderace",
  "Sobble", "Drizzile", "Inteleon",
  "Skwovet", "Greedent",
  "Rookidee", "Corvisquire", "Corviknight",
  "Blipbug", "Dottler", "Orbeetle",
  "Nickit", "Thievul",
  "Gossifleur", "Eldegoss",
  "Wooloo", "Dubwool",
  "Chewtle", "Drednaw",
  "Yamper", "Boltund",
  "Rolycoly", "Carkol", "Coalossal",
  "Applin", "Flapple", "Appletun",
  "Silicobra", "Sandaconda",
  "Cramorant",
  "Arrokuda", "Barraskewda",
  "Toxel", "Toxtricity",
  "Sizzlipede", "Centiskorch",
  "Clobbopus", "Grapploct",
  "Sinistea", "Polteageist",
  "Hatenna", "Hattrem", "Hatterene",
  "Impidimp", "Morgrem", "Grimmsnarl",
  "Obstagoon",
  "Perrserker",
  "Cursola",
  "Sirfetch'd",
  "Runerigus",
  "Milcery", "Alcremie",
  "Falinks",
  "Pincurchin",
  "Snom", "Frosmoth",
  "Stonjourner",
  "Eiscue",
  "Indeedee",
  "Morpeko",
  "Cufant", "Copperajah",
  "Dracozolt", "Arctozolt", "Dracovish", "Arctovish",
  "Duraludon",
  "Dreepy", "Drakloak", "Dragapult",
  "Zacian", "Zamazenta",
  "Eternatus",
  "Kubfu", "Urshifu",
  "Zarude", "Regieleki", "Regidrago",
  "Glastrier", "Spectrier",
  "Calyrex",

  // ── Generation 9 (Paldea) ─────────────────────────────────────────
  "Sprigatito", "Floragato", "Meowscarada",
  "Fuecoco", "Crocalor", "Skeledirge",
  "Quaxly", "Quaxwell", "Quaquaval",
  "Lechonk", "Oinkologne",
  "Tarountula", "Spidops",
  "Nymble", "Lokix",
  "Pawmi", "Pawmo", "Pawmot",
  "Tandemaus", "Maushold",
  "Fidough", "Dachsbun",
  "Smoliv", "Dolliv", "Arboliva",
  "Squawkabilly",
  "Nacli", "Naclstack", "Garganacl",
  "Charcadet", "Armarouge", "Ceruledge",
  "Tadbulb", "Bellibolt",
  "Wattrel", "Kilowattrel",
  "Maschiff", "Mabosstiff",
  "Shroodle", "Grafaiai",
  "Bramblin", "Brambleghast",
  "Toedscool", "Toedscruel",
  "Klawf",
  "Capsakid", "Scovillain",
  "Rellor", "Rabsca",
  "Flittle", "Espathra",
  "Tinkatink", "Tinkatuff", "Tinkaton",
  "Wiglett", "Wugtrio",
  "Bombirdier",
  "Finizen", "Palafin",
  "Varoom", "Revavroom",
  "Cyclizar",
  "Orthworm",
  "Glimmet", "Glimmora",
  "Greavard", "Houndstone",
  "Flamigo",
  "Cetoddle", "Cetitan",
  "Veluza",
  "Dondozo", "Tatsugiri",
  "Annihilape",
  "Clodsire",
  "Farigiraf",
  "Dudunsparce",
  "Kingambit",
  "Great Tusk", "Scream Tail", "Brute Bonnet",
  "Flutter Mane", "Slither Wing", "Sandy Shocks",
  "Iron Treads", "Iron Bundle", "Iron Hands",
  "Iron Jugulis", "Iron Moth", "Iron Thorns",
  "Frigibax", "Arctibax", "Baxcalibur",
  "Gholdengo",
  "Wo-Chien", "Chien-Pao", "Ting-Lu", "Chi-Yu",
  "Roaring Moon", "Iron Valiant",
  "Koraidon", "Miraidon",
  "Walking Wake", "Iron Leaves",
  "Dipplin", "Poltchageist", "Sinistcha",
  "Okidogi", "Munkidori", "Fezandipiti",
  "Ogerpon", "Archaludon", "Hydrapple",
  "Gouging Fire", "Raging Bolt",
  "Iron Boulder", "Iron Crown",
  "Terapagos", "Pecharunt",
];

// ── Aliases (handle common variations / misspellings) ────────────────

const ALIASES: Record<string, string> = {
  // Gen 1
  "nidoran f": "Nidoran♀",
  "nidoran female": "Nidoran♀",
  "nidoran m": "Nidoran♂",
  "nidoran male": "Nidoran♂",
  "farfetchd": "Farfetch'd",
  "farfetch d": "Farfetch'd",
  "mr mime": "Mr. Mime",
  "mrmime": "Mr. Mime",
  "mime": "Mr. Mime",
  "gyrados": "Gyarados",
  "meganium": "Meganium",
  "ho-oh": "Ho-Oh",
  "ho oh": "Ho-Oh",
  "hooh": "Ho-Oh",
  // Gen 2
  "porygon 2": "Porygon2",
  "porygon2": "Porygon2",
  // Gen 4
  "mime jr": "Mime Jr.",
  "mime jr.": "Mime Jr.",
  "mimejr": "Mime Jr.",
  "porygon-z": "Porygon-Z",
  "porygon z": "Porygon-Z",
  "porygonz": "Porygon-Z",
  // Gen 5
  "type null": "Type: Null",
  "typenull": "Type: Null",
  // Gen 7
  "tapu koko": "Tapu Koko",
  "tapu lele": "Tapu Lele",
  "tapu bulu": "Tapu Bulu",
  "tapu fini": "Tapu Fini",
  "jangmo-o": "Jangmo-o",
  "jangmo o": "Jangmo-o",
  "jangmoo": "Jangmo-o",
  "hakamo-o": "Hakamo-o",
  "hakamo o": "Hakamo-o",
  "hakamoo": "Hakamo-o",
  "kommo-o": "Kommo-o",
  "kommo o": "Kommo-o",
  "kommoo": "Kommo-o",
  // Gen 8
  "sirfetchd": "Sirfetch'd",
  "sirfetch d": "Sirfetch'd",
  "sir farfetchd": "Sirfetch'd",
  // Gen 9
  "great tusk": "Great Tusk",
  "scream tail": "Scream Tail",
  "brute bonnet": "Brute Bonnet",
  "flutter mane": "Flutter Mane",
  "slither wing": "Slither Wing",
  "sandy shocks": "Sandy Shocks",
  "iron treads": "Iron Treads",
  "iron bundle": "Iron Bundle",
  "iron hands": "Iron Hands",
  "iron jugulis": "Iron Jugulis",
  "iron moth": "Iron Moth",
  "iron thorns": "Iron Thorns",
  "roaring moon": "Roaring Moon",
  "iron valiant": "Iron Valiant",
  "walking wake": "Walking Wake",
  "iron leaves": "Iron Leaves",
  "gouging fire": "Gouging Fire",
  "raging bolt": "Raging Bolt",
  "iron boulder": "Iron Boulder",
  "iron crown": "Iron Crown",
  "wo-chien": "Wo-Chien",
  "chien-pao": "Chien-Pao",
  "ting-lu": "Ting-Lu",
  "chi-yu": "Chi-Yu",
};

// ── Lookup ──────────────────────────────────────────────────────────

function normalize(name: string): string {
  return name.toLowerCase().trim().replace(/\s+/g, " ");
}

const LOOKUP_MAP: Map<string, string> = new Map();

for (const entry of POKEMON_ENTRIES) {
  LOOKUP_MAP.set(normalize(entry), entry);
}
for (const [alias, target] of Object.entries(ALIASES)) {
  const key = normalize(alias);
  if (!LOOKUP_MAP.has(key)) {
    LOOKUP_MAP.set(key, target);
  }
}

export interface LocalLookupResult {
  valid: true;
  display: string;
}

export function localLookup(name: string): LocalLookupResult | null {
  const key = normalize(name);
  const display = LOOKUP_MAP.get(key);
  if (!display) return null;
  return { valid: true, display };
}

export const DATASET_SIZE = POKEMON_ENTRIES.length;
