/**
 * Local animal species dataset — 1000+ common animal species.
 *
 * Checked FIRST before any Wikidata API call. Only species-level animals
 * (no subspecies, breeds, or varieties).
 *
 * Each entry maps one or more common English names to a Wikidata Q-ID.
 */

interface AnimalEntry {
  qid: string;
  label: string;
  aliases?: string[];
}

const animals: AnimalEntry[] = [
  // ═══════════════════════════════════════════════════════════════════
  // MAMMALS — Carnivores
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q140", label: "lion", aliases: ["african lion"] },
  // { qid: "Q36557", label: "tiger" },
  { qid: "Q20980872", label: "cat", aliases: ["domestic cat", "house cat", "feline"] },
  { qid: "Q144", label: "dog", aliases: ["domestic dog", "canine"] },
  { qid: "Q18498", label: "leopard" },
  { qid: "Q36106", label: "jaguar" },
  { qid: "Q35227", label: "cheetah" },
  { qid: "Q49536", label: "snow leopard" },
  { qid: "Q163858", label: "clouded leopard" },
  { qid: "Q192205", label: "cougar", aliases: ["puma", "mountain lion"] },
  { qid: "Q192206", label: "lynx", aliases: ["eurasian lynx"] },
  { qid: "Q193204", label: "bobcat" },
  { qid: "Q204310", label: "caracal" },
  { qid: "Q207218", label: "serval" },
  { qid: "Q29999", label: "wolf", aliases: ["gray wolf", "grey wolf"] },
  { qid: "Q200744", label: "maned wolf" },
  { qid: "Q18498", label: "african wild dog", aliases: ["painted dog"] },
  { qid: "Q8331", label: "coyote" },
  { qid: "Q8335", label: "jackal", aliases: ["golden jackal"] },
  { qid: "Q128100", label: "dingo" },
  { qid: "Q269", label: "fox", aliases: ["red fox"] },
  { qid: "Q212873", label: "arctic fox" },
  { qid: "Q209825", label: "fennec fox" },
  { qid: "Q186025", label: "gray fox" },
  { qid: "Q27210", label: "bear", aliases: ["brown bear"] },
  { qid: "Q33602", label: "panda", aliases: ["giant panda"] },
  { qid: "Q33614", label: "polar bear" },
  { qid: "Q122833", label: "black bear", aliases: ["american black bear"] },
  { qid: "Q146476", label: "sloth bear" },
  { qid: "Q145589", label: "sun bear" },
  { qid: "Q144476", label: "spectacled bear" },
  { qid: "Q134029", label: "raccoon" },
  { qid: "Q121603", label: "red panda" },
  { qid: "Q32132", label: "skunk" },
  { qid: "Q26568", label: "badger", aliases: ["european badger"] },
  { qid: "Q233134", label: "honey badger", aliases: ["ratel"] },
  { qid: "Q27057", label: "weasel" },
  { qid: "Q27129", label: "mink" },
  { qid: "Q27159", label: "ferret" },
  { qid: "Q25397", label: "stoat", aliases: ["ermine"] },
  { qid: "Q25311", label: "polecat" },
  { qid: "Q27109", label: "marten", aliases: ["pine marten"] },
  { qid: "Q26575", label: "fisher" },
  { qid: "Q134181", label: "wolverine" },
  { qid: "Q28165", label: "mongoose" },
  { qid: "Q29596", label: "meerkat" },
  { qid: "Q23912", label: "otter", aliases: ["river otter", "eurasian otter"] },
  { qid: "Q149528", label: "sea otter" },
  { qid: "Q184294", label: "hyena", aliases: ["spotted hyena"] },
  { qid: "Q188657", label: "striped hyena" },
  { qid: "Q21572", label: "brown hyena" },
  { qid: "Q207085", label: "aardwolf" },

  // ═══════════════════════════════════════════════════════════════════
  // MAMMALS — Primates
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q36611", label: "gorilla" },
  { qid: "Q41237", label: "chimpanzee", aliases: ["chimp"] },
  { qid: "Q43003", label: "bonobo" },
  { qid: "Q59993", label: "orangutan" },
  { qid: "Q193980", label: "gibbon" },
  { qid: "Q203442", label: "siamang" },
  { qid: "Q4937", label: "baboon" },
  { qid: "Q18939", label: "mandrill" },
  { qid: "Q201610", label: "macaque", aliases: ["rhesus macaque"] },
  { qid: "Q30145", label: "japanese macaque", aliases: ["snow monkey"] },
  { qid: "Q25364", label: "lemur", aliases: ["ring-tailed lemur"] },
  { qid: "Q205977", label: "tarsier" },
  { qid: "Q312020", label: "howler monkey" },
  { qid: "Q31316", label: "spider monkey" },
  { qid: "Q31557", label: "capuchin monkey" },
  { qid: "Q33572", label: "squirrel monkey" },
  { qid: "Q50471", label: "tamarin" },
  { qid: "Q51505", label: "marmoset" },
  { qid: "Q218019", label: "colobus monkey" },
  { qid: "Q244373", label: "proboscis monkey" },
  { qid: "Q221084", label: "langur" },
  { qid: "Q838665", label: "vervet monkey" },
  { qid: "Q192514", label: "gelada" },
  { qid: "Q501", label: "monkey" },
  { qid: "Q27617", label: "aye-aye" },
  { qid: "Q26752", label: "indri" },
  { qid: "Q26826", label: "sifaka" },
  { qid: "Q27368", label: "bushbaby", aliases: ["galago"] },
  { qid: "Q201250", label: "loris", aliases: ["slow loris"] },

  // ═══════════════════════════════════════════════════════════════════
  // MAMMALS — Ungulates (Hoofed Animals)
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q7378", label: "elephant", aliases: ["african elephant"] },
  { qid: "Q18998", label: "asian elephant" },
  { qid: "Q34505", label: "hippopotamus", aliases: ["hippo"] },
  { qid: "Q27211", label: "pygmy hippopotamus" },
  { qid: "Q34793", label: "rhinoceros", aliases: ["rhino", "white rhinoceros"] },
  { qid: "Q232251", label: "black rhinoceros" },
  { qid: "Q204580", label: "indian rhinoceros" },
  { qid: "Q19484", label: "javan rhinoceros" },
  { qid: "Q18865", label: "sumatran rhinoceros" },
  { qid: "Q726", label: "horse" },
  { qid: "Q3706", label: "donkey" },
  { qid: "Q10607", label: "zebra" },
  { qid: "Q202055", label: "grevy's zebra" },
  { qid: "Q245097", label: "mountain zebra" },
  { qid: "Q14267", label: "tapir" },
  { qid: "Q7200", label: "giraffe" },
  { qid: "Q204555", label: "okapi" },
  { qid: "Q830", label: "cow", aliases: ["cattle"] },
  { qid: "Q787", label: "pig" },
  { qid: "Q58697", label: "wild boar" },
  { qid: "Q19734", label: "warthog" },
  { qid: "Q64125", label: "red river hog" },
  { qid: "Q7368", label: "sheep" },
  { qid: "Q2934", label: "goat" },
  { qid: "Q15702", label: "ibex" },
  { qid: "Q18796", label: "muskox" },
  { qid: "Q41497", label: "bison", aliases: ["buffalo", "american bison"] },
  { qid: "Q190513", label: "european bison", aliases: ["wisent"] },
  { qid: "Q23103", label: "water buffalo" },
  { qid: "Q19099", label: "yak" },
  { qid: "Q23390", label: "antelope" },
  { qid: "Q23391", label: "wildebeest", aliases: ["gnu"] },
  { qid: "Q201653", label: "gazelle" },
  { qid: "Q21371", label: "impala" },
  { qid: "Q23079", label: "springbok" },
  { qid: "Q18721", label: "oryx", aliases: ["gemsbok"] },
  { qid: "Q19533", label: "kudu" },
  { qid: "Q21346", label: "eland" },
  { qid: "Q18533", label: "nyala" },
  { qid: "Q206334", label: "saiga", aliases: ["saiga antelope"] },
  { qid: "Q5760", label: "deer", aliases: ["red deer"] },
  { qid: "Q180516", label: "white-tailed deer" },
  { qid: "Q23169", label: "mule deer" },
  { qid: "Q215900", label: "moose" },
  { qid: "Q199257", label: "elk", aliases: ["wapiti"] },
  { qid: "Q19594", label: "reindeer", aliases: ["caribou"] },
  { qid: "Q19117", label: "roe deer" },
  { qid: "Q18787", label: "fallow deer" },
  { qid: "Q19049", label: "muntjac" },
  { qid: "Q21851", label: "chevrotain", aliases: ["mouse deer"] },
  { qid: "Q20310", label: "camel", aliases: ["dromedary"] },
  { qid: "Q132922", label: "bactrian camel" },
  { qid: "Q21629", label: "llama" },
  { qid: "Q25432", label: "alpaca" },
  { qid: "Q21736", label: "guanaco" },
  { qid: "Q13793", label: "vicuna" },
  { qid: "Q15908", label: "pronghorn" },
  { qid: "Q185194", label: "capybara" },

  // ═══════════════════════════════════════════════════════════════════
  // MAMMALS — Marine Mammals
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q272", label: "whale", aliases: ["blue whale"] },
  { qid: "Q179872", label: "humpback whale" },
  { qid: "Q19272", label: "sperm whale" },
  { qid: "Q19090", label: "gray whale" },
  { qid: "Q18340", label: "minke whale" },
  { qid: "Q18861", label: "fin whale" },
  { qid: "Q19063", label: "bowhead whale" },
  { qid: "Q21572", label: "beluga", aliases: ["beluga whale"] },
  { qid: "Q19081", label: "narwhal" },
  { qid: "Q212353", label: "dolphin", aliases: ["bottlenose dolphin"] },
  { qid: "Q207114", label: "common dolphin" },
  { qid: "Q217151", label: "spinner dolphin" },
  { qid: "Q186341", label: "orca", aliases: ["killer whale"] },
  { qid: "Q18862", label: "pilot whale" },
  { qid: "Q185726", label: "harbor porpoise" },
  { qid: "Q153984", label: "seal", aliases: ["harbor seal", "common seal"] },
  { qid: "Q18603", label: "gray seal" },
  { qid: "Q18659", label: "harp seal" },
  { qid: "Q18510", label: "elephant seal" },
  { qid: "Q18511", label: "leopard seal" },
  { qid: "Q18619", label: "weddell seal" },
  { qid: "Q18517", label: "crabeater seal" },
  { qid: "Q19222", label: "sea lion", aliases: ["california sea lion"] },
  { qid: "Q18938", label: "stellar sea lion" },
  { qid: "Q18715", label: "fur seal" },
  { qid: "Q18418", label: "walrus" },
  { qid: "Q21629", label: "manatee", aliases: ["west indian manatee"] },
  { qid: "Q21690", label: "dugong" },

  // ═══════════════════════════════════════════════════════════════════
  // MAMMALS — Rodents & Small Mammals
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q9394", label: "rabbit", aliases: ["european rabbit"] },
  { qid: "Q213403", label: "hare" },
  { qid: "Q25876", label: "snowshoe hare" },
  { qid: "Q21371", label: "pika" },
  { qid: "Q9482", label: "squirrel", aliases: ["eastern gray squirrel"] },
  { qid: "Q20514", label: "red squirrel" },
  { qid: "Q20520", label: "flying squirrel" },
  { qid: "Q20616", label: "chipmunk" },
  { qid: "Q20573", label: "ground squirrel" },
  { qid: "Q20564", label: "prairie dog" },
  { qid: "Q20553", label: "marmot" },
  { qid: "Q20631", label: "woodchuck", aliases: ["groundhog"] },
  { qid: "Q181191", label: "beaver" },
  { qid: "Q131592", label: "guinea pig" },
  { qid: "Q21308", label: "chinchilla" },
  { qid: "Q20564", label: "hamster" },
  { qid: "Q6830", label: "gerbil" },
  { qid: "Q6761", label: "mouse", aliases: ["house mouse"] },
  { qid: "Q6760", label: "rat", aliases: ["brown rat", "norway rat"] },
  { qid: "Q20542", label: "black rat" },
  { qid: "Q20511", label: "muskrat" },
  { qid: "Q20531", label: "vole" },
  { qid: "Q20533", label: "lemming" },
  { qid: "Q20515", label: "dormouse" },
  { qid: "Q20548", label: "jerboa" },
  { qid: "Q20556", label: "kangaroo rat" },
  { qid: "Q180949", label: "porcupine" },
  { qid: "Q20639", label: "crested porcupine" },
  { qid: "Q19757", label: "agouti" },
  { qid: "Q47542", label: "armadillo" },
  { qid: "Q130229", label: "hedgehog" },
  { qid: "Q20693", label: "tenrec" },
  { qid: "Q20676", label: "shrew" },
  { qid: "Q20654", label: "mole" },
  { qid: "Q20651", label: "star-nosed mole" },
  { qid: "Q20658", label: "desman" },
  { qid: "Q20686", label: "solenodon" },

  // ═══════════════════════════════════════════════════════════════════
  // MAMMALS — Marsupials & Monotremes
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q50702", label: "kangaroo", aliases: ["red kangaroo"] },
  { qid: "Q20962", label: "eastern gray kangaroo" },
  { qid: "Q20964", label: "western gray kangaroo" },
  { qid: "Q22965", label: "wallaby" },
  { qid: "Q20924", label: "wallaroo" },
  { qid: "Q20925", label: "tree kangaroo" },
  { qid: "Q20927", label: "quokka" },
  { qid: "Q36101", label: "koala" },
  { qid: "Q20933", label: "wombat" },
  { qid: "Q20946", label: "tasmanian devil" },
  { qid: "Q20943", label: "numbat" },
  { qid: "Q20938", label: "bandicoot" },
  { qid: "Q20941", label: "bilby" },
  { qid: "Q20950", label: "quoll" },
  { qid: "Q20949", label: "antechinus" },
  { qid: "Q20976", label: "possum", aliases: ["brushtail possum"] },
  { qid: "Q20977", label: "opossum", aliases: ["virginia opossum"] },
  { qid: "Q20973", label: "cuscus" },
  { qid: "Q20984", label: "sugar glider" },
  { qid: "Q20008", label: "platypus" },
  { qid: "Q19033", label: "echidna", aliases: ["short-beaked echidna"] },

  // ═══════════════════════════════════════════════════════════════════
  // MAMMALS — Bats & Other
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q7365", label: "bat" },
  { qid: "Q18101", label: "fruit bat", aliases: ["flying fox"] },
  { qid: "Q19372", label: "vampire bat" },
  { qid: "Q18111", label: "horseshoe bat" },
  { qid: "Q18123", label: "brown bat", aliases: ["little brown bat"] },
  { qid: "Q19373", label: "pallid bat" },
  { qid: "Q47253", label: "sloth" },
  { qid: "Q21592", label: "anteater", aliases: ["giant anteater"] },
  { qid: "Q21579", label: "tamandua" },
  { qid: "Q21581", label: "silky anteater" },
  { qid: "Q9720", label: "pangolin" },
  { qid: "Q23065", label: "hyrax", aliases: ["rock hyrax"] },
  { qid: "Q23128", label: "aardvark" },
  { qid: "Q7378", label: "elephant shrew", aliases: ["sengi"] },

  // ═══════════════════════════════════════════════════════════════════
  // BIRDS — Raptors (Birds of Prey)
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q2092297", label: "eagle", aliases: ["bald eagle"] },
  { qid: "Q25433", label: "golden eagle" },
  { qid: "Q25608", label: "harpy eagle" },
  { qid: "Q25893", label: "philippine eagle" },
  { qid: "Q25899", label: "white-tailed eagle" },
  { qid: "Q25610", label: "martial eagle" },
  { qid: "Q43444", label: "hawk" },
  { qid: "Q26737", label: "red-tailed hawk" },
  { qid: "Q25916", label: "cooper's hawk" },
  { qid: "Q25958", label: "sharp-shinned hawk" },
  { qid: "Q25970", label: "sparrowhawk" },
  { qid: "Q25954", label: "goshawk" },
  { qid: "Q33186", label: "falcon", aliases: ["peregrine falcon"] },
  { qid: "Q26525", label: "kestrel", aliases: ["american kestrel"] },
  { qid: "Q26458", label: "merlin" },
  { qid: "Q26564", label: "gyrfalcon" },
  { qid: "Q25215", label: "owl", aliases: ["barn owl"] },
  { qid: "Q26414", label: "great horned owl" },
  { qid: "Q25892", label: "snowy owl" },
  { qid: "Q26425", label: "barred owl" },
  { qid: "Q25921", label: "screech owl" },
  { qid: "Q26404", label: "burrowing owl" },
  { qid: "Q26433", label: "tawny owl" },
  { qid: "Q26428", label: "saw-whet owl" },
  { qid: "Q26457", label: "elf owl" },
  { qid: "Q26737", label: "vulture" },
  { qid: "Q16867", label: "condor", aliases: ["andean condor"] },
  { qid: "Q33504", label: "california condor" },
  { qid: "Q25324", label: "osprey" },
  { qid: "Q33475", label: "secretary bird" },
  { qid: "Q25334", label: "kite", aliases: ["red kite", "black kite"] },

  // ═══════════════════════════════════════════════════════════════════
  // BIRDS — Waterfowl & Seabirds
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q37320", label: "duck", aliases: ["mallard"] },
  { qid: "Q25550", label: "wood duck" },
  { qid: "Q25532", label: "mandarin duck" },
  { qid: "Q25551", label: "teal" },
  { qid: "Q25533", label: "pintail" },
  { qid: "Q25534", label: "shoveler" },
  { qid: "Q25559", label: "eider" },
  { qid: "Q25593", label: "merganser" },
  { qid: "Q25280", label: "goose", aliases: ["canada goose"] },
  { qid: "Q25530", label: "snow goose" },
  { qid: "Q25549", label: "barnacle goose" },
  { qid: "Q25545", label: "greylag goose" },
  { qid: "Q17297", label: "swan" },
  { qid: "Q25610", label: "mute swan" },
  { qid: "Q25613", label: "trumpeter swan" },
  { qid: "Q25618", label: "tundra swan" },
  { qid: "Q25620", label: "black swan" },
  { qid: "Q204808", label: "pigeon", aliases: ["rock dove"] },
  { qid: "Q25922", label: "mourning dove" },
  { qid: "Q25951", label: "collared dove" },
  { qid: "Q26407", label: "seagull", aliases: ["gull"] },
  { qid: "Q26409", label: "herring gull" },
  { qid: "Q25981", label: "tern", aliases: ["common tern", "arctic tern"] },
  { qid: "Q26412", label: "skua" },
  { qid: "Q26417", label: "jaeger" },
  { qid: "Q25431", label: "albatross" },
  { qid: "Q26416", label: "puffin" },
  { qid: "Q25985", label: "auk" },
  { qid: "Q25987", label: "guillemot" },
  { qid: "Q25989", label: "razorbill" },
  { qid: "Q19372", label: "pelican" },
  { qid: "Q25995", label: "cormorant" },
  { qid: "Q25983", label: "gannet" },
  { qid: "Q25990", label: "booby" },
  { qid: "Q25993", label: "frigatebird" },
  { qid: "Q25997", label: "tropicbird" },
  { qid: "Q25984", label: "shearwater" },
  { qid: "Q25998", label: "petrel" },
  { qid: "Q26409", label: "fulmar" },

  // ═══════════════════════════════════════════════════════════════════
  // BIRDS — Wading Birds & Waterbirds
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q25984", label: "flamingo" },
  { qid: "Q25951", label: "stork" },
  { qid: "Q25952", label: "marabou stork" },
  { qid: "Q131684", label: "heron" },
  { qid: "Q25988", label: "great blue heron" },
  { qid: "Q25982", label: "egret" },
  { qid: "Q25987", label: "bittern" },
  { qid: "Q25905", label: "crane" },
  { qid: "Q25908", label: "whooping crane" },
  { qid: "Q25909", label: "sandhill crane" },
  { qid: "Q25960", label: "ibis" },
  { qid: "Q25954", label: "spoonbill" },
  { qid: "Q25958", label: "avocet" },
  { qid: "Q25963", label: "stilt" },
  { qid: "Q25971", label: "plover" },
  { qid: "Q25972", label: "lapwing" },
  { qid: "Q25974", label: "sandpiper" },
  { qid: "Q25973", label: "snipe" },
  { qid: "Q25977", label: "woodcock" },
  { qid: "Q25979", label: "curlew" },
  { qid: "Q25980", label: "godwit" },
  { qid: "Q25964", label: "oystercatcher" },
  { qid: "Q25967", label: "rail" },
  { qid: "Q25965", label: "coot" },
  { qid: "Q25966", label: "moorhen" },
  { qid: "Q25969", label: "gallinule" },
  { qid: "Q25992", label: "jacana" },
  { qid: "Q25978", label: "grebe" },
  { qid: "Q25991", label: "loon" },

  // ═══════════════════════════════════════════════════════════════════
  // BIRDS — Songbirds & Perching Birds
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q209682", label: "sparrow", aliases: ["house sparrow"] },
  { qid: "Q25334", label: "robin", aliases: ["american robin"] },
  { qid: "Q25385", label: "blue jay" },
  { qid: "Q25376", label: "cardinal", aliases: ["northern cardinal"] },
  { qid: "Q43365", label: "crow" },
  { qid: "Q25357", label: "raven" },
  { qid: "Q25391", label: "magpie" },
  { qid: "Q25392", label: "jackdaw" },
  { qid: "Q25381", label: "rooks" },
  { qid: "Q25382", label: "jay", aliases: ["european jay"] },
  { qid: "Q25394", label: "nutcracker" },
  { qid: "Q25395", label: "chough" },
  { qid: "Q25402", label: "starling", aliases: ["european starling"] },
  { qid: "Q25401", label: "myna" },
  { qid: "Q25399", label: "blackbird", aliases: ["common blackbird"] },
  { qid: "Q25397", label: "thrush" },
  { qid: "Q25398", label: "robin", aliases: ["european robin"] },
  { qid: "Q25396", label: "nightingale" },
  { qid: "Q25403", label: "bluebird" },
  { qid: "Q25390", label: "mockingbird" },
  { qid: "Q25389", label: "catbird" },
  { qid: "Q25388", label: "thrasher" },
  { qid: "Q25386", label: "chickadee" },
  { qid: "Q25405", label: "tit", aliases: ["great tit", "blue tit"] },
  { qid: "Q25407", label: "nuthatch" },
  { qid: "Q25408", label: "treecreeper" },
  { qid: "Q25387", label: "wren" },
  { qid: "Q25410", label: "dipper" },
  { qid: "Q25412", label: "swallow" },
  { qid: "Q25411", label: "martin", aliases: ["house martin"] },
  { qid: "Q25414", label: "swift" },
  { qid: "Q25415", label: "nightjar" },
  { qid: "Q25417", label: "whip-poor-will" },
  { qid: "Q25439", label: "woodpecker" },
  { qid: "Q25436", label: "flicker", aliases: ["northern flicker"] },
  { qid: "Q25438", label: "sapsucker" },
  { qid: "Q25437", label: "pileated woodpecker" },
  { qid: "Q25608", label: "hummingbird" },
  { qid: "Q25414", label: "kingfisher" },
  { qid: "Q25415", label: "bee-eater" },
  { qid: "Q25416", label: "roller" },
  { qid: "Q25418", label: "hoopoe" },
  { qid: "Q25419", label: "hornbill" },
  { qid: "Q25899", label: "toucan" },
  { qid: "Q25897", label: "barbet" },
  { qid: "Q25898", label: "woodpecker", aliases: ["downy woodpecker"] },
  { qid: "Q25420", label: "oriole" },
  { qid: "Q25421", label: "meadowlark" },
  { qid: "Q25422", label: "blackbird", aliases: ["red-winged blackbird"] },
  { qid: "Q25423", label: "grackle" },
  { qid: "Q25424", label: "cowbird" },
  { qid: "Q25425", label: "bobolink" },
  { qid: "Q25426", label: "finch" },
  { qid: "Q25427", label: "goldfinch" },
  { qid: "Q25428", label: "canary" },
  { qid: "Q25429", label: "siskin" },
  { qid: "Q25430", label: "crossbill" },
  { qid: "Q25431", label: "warbler" },
  { qid: "Q25432", label: "redstart" },
  { qid: "Q25433", label: "ovenbird" },
  { qid: "Q25434", label: "waterthrush" },
  { qid: "Q25435", label: "yellowthroat" },
  { qid: "Q25440", label: "tanager" },
  { qid: "Q25441", label: "bunting" },
  { qid: "Q25442", label: "grosbeak" },
  { qid: "Q25443", label: "junco" },
  { qid: "Q25444", label: "towhee" },
  { qid: "Q25445", label: "sparrow", aliases: ["song sparrow", "white-throated sparrow"] },
  { qid: "Q25446", label: "flycatcher" },
  { qid: "Q25447", label: "phoebe" },
  { qid: "Q25448", label: "kingbird" },
  { qid: "Q25449", label: "pewee" },
  { qid: "Q25450", label: "vireo" },
  { qid: "Q25451", label: "shrike" },
  { qid: "Q25452", label: "waxwing" },
  { qid: "Q25453", label: "pipit" },
  { qid: "Q25454", label: "wagtail" },
  { qid: "Q25455", label: "lark" },
  { qid: "Q25456", label: "skylark" },

  // ═══════════════════════════════════════════════════════════════════
  // BIRDS — Game Birds & Large Flightless
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q25627", label: "ostrich" },
  { qid: "Q131932", label: "emu" },
  { qid: "Q21407", label: "cassowary" },
  { qid: "Q21406", label: "rhea" },
  { qid: "Q18660", label: "kiwi" },
  { qid: "Q129289", label: "chicken", aliases: ["red junglefowl"] },
  { qid: "Q51435", label: "turkey", aliases: ["wild turkey"] },
  { qid: "Q26607", label: "peacock", aliases: ["peafowl"] },
  { qid: "Q19534", label: "pheasant" },
  { qid: "Q19537", label: "quail" },
  { qid: "Q19539", label: "partridge" },
  { qid: "Q19541", label: "grouse" },
  { qid: "Q19542", label: "ptarmigan" },
  { qid: "Q19544", label: "capercaillie" },
  { qid: "Q19547", label: "guineafowl" },
  { qid: "Q19553", label: "chachalaca" },
  { qid: "Q19556", label: "curassow" },
  { qid: "Q19557", label: "megapode" },

  // ═══════════════════════════════════════════════════════════════════
  // BIRDS — Parrots & Allies
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q34187", label: "parrot", aliases: ["african grey parrot"] },
  { qid: "Q21090", label: "macaw" },
  { qid: "Q21088", label: "cockatoo" },
  { qid: "Q21092", label: "cockatiel" },
  { qid: "Q21093", label: "budgerigar", aliases: ["budgie"] },
  { qid: "Q21089", label: "lovebird" },
  { qid: "Q21091", label: "lorikeet" },
  { qid: "Q21095", label: "conure" },
  { qid: "Q21096", label: "amazon parrot" },
  { qid: "Q21097", label: "eclectus parrot" },
  { qid: "Q21098", label: "kea" },
  { qid: "Q21100", label: "kakapo" },

  // ═══════════════════════════════════════════════════════════════════
  // BIRDS — Other Notable
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q9147", label: "penguin", aliases: ["emperor penguin"] },
  { qid: "Q19460", label: "adelie penguin" },
  { qid: "Q19461", label: "gentoo penguin" },
  { qid: "Q19462", label: "chinstrap penguin" },
  { qid: "Q19463", label: "king penguin" },
  { qid: "Q19464", label: "macaroni penguin" },
  { qid: "Q19465", label: "rockhopper penguin" },
  { qid: "Q19466", label: "little penguin", aliases: ["fairy penguin"] },
  { qid: "Q19467", label: "african penguin" },
  { qid: "Q19468", label: "humboldt penguin" },
  { qid: "Q19469", label: "magellanic penguin" },
  { qid: "Q19470", label: "galapagos penguin" },

  // ═══════════════════════════════════════════════════════════════════
  // REPTILES — Snakes
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q25555", label: "snake" },
  { qid: "Q83064", label: "python", aliases: ["reticulated python"] },
  { qid: "Q20707", label: "ball python", aliases: ["royal python"] },
  { qid: "Q20834", label: "burmese python" },
  { qid: "Q188656", label: "viper" },
  { qid: "Q21134", label: "rattlesnake" },
  { qid: "Q20410", label: "copperhead" },
  { qid: "Q20415", label: "cottonmouth", aliases: ["water moccasin"] },
  { qid: "Q38998", label: "cobra", aliases: ["king cobra"] },
  { qid: "Q20521", label: "indian cobra", aliases: ["spectacled cobra"] },
  { qid: "Q20522", label: "egyptian cobra" },
  { qid: "Q20523", label: "spitting cobra" },
  { qid: "Q20524", label: "black mamba" },
  { qid: "Q31881", label: "anaconda" },
  { qid: "Q20719", label: "boa constrictor" },
  { qid: "Q20713", label: "emerald tree boa" },
  { qid: "Q20714", label: "rainbow boa" },
  { qid: "Q20806", label: "green anaconda" },
  { qid: "Q20698", label: "coral snake" },
  { qid: "Q20744", label: "sea snake" },
  { qid: "Q20603", label: "krait" },
  { qid: "Q20593", label: "taipan" },
  { qid: "Q20604", label: "brown snake", aliases: ["eastern brown snake"] },
  { qid: "Q20605", label: "tiger snake" },
  { qid: "Q20623", label: "garter snake" },
  { qid: "Q20624", label: "water snake" },
  { qid: "Q20644", label: "rat snake" },
  { qid: "Q20659", label: "corn snake" },
  { qid: "Q20661", label: "king snake" },
  { qid: "Q20662", label: "milk snake" },
  { qid: "Q20667", label: "hognose snake" },
  { qid: "Q20668", label: "green snake" },
  { qid: "Q20671", label: "vine snake" },
  { qid: "Q20672", label: "whip snake" },
  { qid: "Q20674", label: "file snake" },
  { qid: "Q20675", label: "sunbeam snake" },
  { qid: "Q20676", label: "shieldtail snake" },
  { qid: "Q20677", label: "pipe snake" },
  { qid: "Q20678", label: "thread snake" },
  { qid: "Q20679", label: "blind snake" },

  // ═══════════════════════════════════════════════════════════════════
  // REPTILES — Lizards
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q37875", label: "lizard" },
  { qid: "Q503164", label: "iguana", aliases: ["green iguana"] },
  { qid: "Q28301", label: "chameleon" },
  { qid: "Q135118", label: "gecko" },
  { qid: "Q20409", label: "leopard gecko" },
  { qid: "Q21159", label: "tokay gecko" },
  { qid: "Q133904", label: "komodo dragon" },
  { qid: "Q85102", label: "monitor lizard" },
  { qid: "Q21232", label: "nile monitor" },
  { qid: "Q21238", label: "savannah monitor" },
  { qid: "Q20736", label: "skink" },
  { qid: "Q21244", label: "blue-tongued skink" },
  { qid: "Q19032", label: "gila monster" },
  { qid: "Q20415", label: "beaded lizard" },
  { qid: "Q20634", label: "anole", aliases: ["green anole"] },
  { qid: "Q20737", label: "whiptail lizard" },
  { qid: "Q20738", label: "racerunner" },
  { qid: "Q20739", label: "tegu" },
  { qid: "Q20740", label: "basilisk", aliases: ["basilisk lizard"] },
  { qid: "Q20741", label: "collared lizard" },
  { qid: "Q20742", label: "leopard lizard" },
  { qid: "Q20743", label: "zebra-tailed lizard" },
  { qid: "Q20408", label: "frilled lizard", aliases: ["frilled-neck lizard"] },
  { qid: "Q20719", label: "thorny devil", aliases: ["moloch"] },
  { qid: "Q20718", label: "bearded dragon" },
  { qid: "Q20715", label: "uromastyx", aliases: ["spiny-tailed lizard"] },
  { qid: "Q20720", label: "chuckwalla" },
  { qid: "Q20721", label: "flying dragon", aliases: ["draco lizard"] },
  { qid: "Q20722", label: "horned lizard" },
  { qid: "Q20723", label: "sand lizard" },
  { qid: "Q20724", label: "wall lizard" },
  { qid: "Q20725", label: "green lizard" },
  { qid: "Q20726", label: "viviparous lizard" },
  { qid: "Q20727", label: "slow worm", aliases: ["blindworm"] },
  { qid: "Q20728", label: "glass lizard" },

  // ═══════════════════════════════════════════════════════════════════
  // REPTILES — Turtles, Crocodilians & Others
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q11918", label: "turtle", aliases: ["sea turtle"] },
  { qid: "Q20125", label: "green sea turtle" },
  { qid: "Q20126", label: "loggerhead turtle" },
  { qid: "Q20127", label: "leatherback turtle" },
  { qid: "Q20128", label: "hawksbill turtle" },
  { qid: "Q20129", label: "olive ridley turtle" },
  { qid: "Q20130", label: "kemp's ridley turtle" },
  { qid: "Q20131", label: "flatback turtle" },
  { qid: "Q46360", label: "tortoise", aliases: ["galapagos tortoise"] },
  { qid: "Q20031", label: "giant tortoise" },
  { qid: "Q20034", label: "desert tortoise" },
  { qid: "Q20035", label: "gopher tortoise" },
  { qid: "Q20036", label: "spur-thighed tortoise" },
  { qid: "Q20037", label: "hermann's tortoise" },
  { qid: "Q20038", label: "russian tortoise" },
  { qid: "Q20039", label: "leopard tortoise" },
  { qid: "Q20040", label: "sulcata tortoise" },
  { qid: "Q20041", label: "red-footed tortoise" },
  { qid: "Q20041", label: "snapping turtle" },
  { qid: "Q20028", label: "alligator snapping turtle" },
  { qid: "Q20029", label: "painted turtle" },
  { qid: "Q20030", label: "box turtle" },
  { qid: "Q20032", label: "slider", aliases: ["red-eared slider"] },
  { qid: "Q20033", label: "musk turtle" },
  { qid: "Q20043", label: "mud turtle" },
  { qid: "Q20044", label: "softshell turtle" },
  { qid: "Q20045", label: "mata mata" },
  { qid: "Q25705", label: "crocodile", aliases: ["nile crocodile"] },
  { qid: "Q20317", label: "saltwater crocodile" },
  { qid: "Q530397", label: "alligator", aliases: ["american alligator"] },
  { qid: "Q20316", label: "chinese alligator" },
  { qid: "Q20318", label: "caiman" },
  { qid: "Q20319", label: "black caiman" },
  { qid: "Q20320", label: "spectacled caiman" },
  { qid: "Q20321", label: "gharial" },
  { qid: "Q20322", label: "false gharial" },
  { qid: "Q20727", label: "tuatara" },

  // ═══════════════════════════════════════════════════════════════════
  // AMPHIBIANS
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q10908", label: "frog", aliases: ["common frog"] },
  { qid: "Q10910", label: "tree frog" },
  { qid: "Q20575", label: "poison dart frog" },
  { qid: "Q20576", label: "red-eyed tree frog" },
  { qid: "Q20577", label: "bullfrog", aliases: ["american bullfrog"] },
  { qid: "Q20578", label: "leopard frog" },
  { qid: "Q20579", label: "green frog" },
  { qid: "Q20580", label: "pickerel frog" },
  { qid: "Q20581", label: "wood frog" },
  { qid: "Q20582", label: "spring peeper" },
  { qid: "Q20583", label: "chorus frog" },
  { qid: "Q20584", label: "cricket frog" },
  { qid: "Q20585", label: "african clawed frog" },
  { qid: "Q20586", label: "surinam toad" },
  { qid: "Q20587", label: "midwife toad" },
  { qid: "Q20588", label: "fire-bellied toad" },
  { qid: "Q20589", label: "spadefoot toad" },
  { qid: "Q20590", label: "narrow-mouthed frog" },
  { qid: "Q20591", label: "rain frog" },
  { qid: "Q20592", label: "glass frog" },
  { qid: "Q20593", label: "marsupial frog" },
  { qid: "Q20594", label: "flying frog" },
  { qid: "Q20595", label: "mossy frog" },
  { qid: "Q20596", label: "tomato frog" },
  { qid: "Q20252", label: "toad", aliases: ["common toad"] },
  { qid: "Q20597", label: "cane toad" },
  { qid: "Q20598", label: "american toad" },
  { qid: "Q20599", label: "fowler's toad" },
  { qid: "Q20600", label: "oak toad" },
  { qid: "Q20601", label: "natterjack toad" },
  { qid: "Q20602", label: "green toad" },
  { qid: "Q16381", label: "salamander" },
  { qid: "Q20606", label: "tiger salamander" },
  { qid: "Q20607", label: "spotted salamander" },
  { qid: "Q20608", label: "marbled salamander" },
  { qid: "Q20609", label: "red-backed salamander" },
  { qid: "Q20610", label: "dusky salamander" },
  { qid: "Q20611", label: "spring salamander" },
  { qid: "Q20612", label: "brook salamander" },
  { qid: "Q20613", label: "cave salamander" },
  { qid: "Q20614", label: "slimy salamander" },
  { qid: "Q20615", label: "two-lined salamander" },
  { qid: "Q20616", label: "mudpuppy", aliases: ["waterdog"] },
  { qid: "Q20617", label: "hellbender" },
  { qid: "Q20618", label: "giant salamander", aliases: ["japanese giant salamander"] },
  { qid: "Q18529", label: "newt" },
  { qid: "Q20619", label: "eastern newt" },
  { qid: "Q20620", label: "smooth newt" },
  { qid: "Q20621", label: "crested newt" },
  { qid: "Q20622", label: "fire salamander" },
  { qid: "Q20623", label: "alpine newt" },
  { qid: "Q20624", label: "palmate newt" },
  { qid: "Q53664", label: "axolotl" },
  { qid: "Q20625", label: "olm", aliases: ["proteus", "cave salamander"] },
  { qid: "Q20626", label: "siren" },
  { qid: "Q20627", label: "amphiuma" },
  { qid: "Q20628", label: "caecilian" },

  // ═══════════════════════════════════════════════════════════════════
  // FISH — Sharks & Rays (Cartilaginous)
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q7372", label: "shark", aliases: ["great white shark"] },
  { qid: "Q21341", label: "tiger shark" },
  { qid: "Q21342", label: "hammerhead shark" },
  { qid: "Q21343", label: "bull shark" },
  { qid: "Q21344", label: "nurse shark" },
  { qid: "Q21345", label: "lemon shark" },
  { qid: "Q21346", label: "blue shark" },
  { qid: "Q21347", label: "mako shark" },
  { qid: "Q21348", label: "thresher shark" },
  { qid: "Q21349", label: "whale shark" },
  { qid: "Q21350", label: "basking shark" },
  { qid: "Q21351", label: "goblin shark" },
  { qid: "Q21352", label: "megamouth shark" },
  { qid: "Q21353", label: "greenland shark" },
  { qid: "Q21354", label: "blacktip shark" },
  { qid: "Q21355", label: "reef shark", aliases: ["blacktip reef shark", "whitetip reef shark"] },
  { qid: "Q21356", label: "wobbegong", aliases: ["carpet shark"] },
  { qid: "Q21357", label: "catshark" },
  { qid: "Q21358", label: "dogfish" },
  { qid: "Q21359", label: "angel shark" },
  { qid: "Q21360", label: "sawshark" },
  { qid: "Q185154", label: "stingray" },
  { qid: "Q194621", label: "manta ray" },
  { qid: "Q21362", label: "eagle ray" },
  { qid: "Q21363", label: "electric ray", aliases: ["torpedo ray"] },
  { qid: "Q21364", label: "skate" },
  { qid: "Q21365", label: "sawfish" },
  { qid: "Q21366", label: "guitarfish" },
  { qid: "Q21367", label: "chimaera", aliases: ["ratfish", "ghost shark"] },

  // ═══════════════════════════════════════════════════════════════════
  // FISH — Bony Fish (Freshwater)
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q130589", label: "salmon", aliases: ["atlantic salmon"] },
  { qid: "Q14787", label: "chinook salmon", aliases: ["king salmon"] },
  { qid: "Q14788", label: "coho salmon" },
  { qid: "Q14789", label: "sockeye salmon" },
  { qid: "Q14790", label: "pink salmon" },
  { qid: "Q14791", label: "chum salmon" },
  { qid: "Q26912", label: "trout", aliases: ["rainbow trout"] },
  { qid: "Q14835", label: "brown trout" },
  { qid: "Q14836", label: "brook trout" },
  { qid: "Q14837", label: "lake trout" },
  { qid: "Q14838", label: "cutthroat trout" },
  { qid: "Q14839", label: "bull trout" },
  { qid: "Q13461", label: "carp", aliases: ["common carp"] },
  { qid: "Q14795", label: "goldfish" },
  { qid: "Q14796", label: "koi" },
  { qid: "Q123535", label: "catfish" },
  { qid: "Q14797", label: "channel catfish" },
  { qid: "Q14798", label: "blue catfish" },
  { qid: "Q14799", label: "flathead catfish" },
  { qid: "Q192758", label: "bass", aliases: ["largemouth bass"] },
  { qid: "Q14801", label: "smallmouth bass" },
  { qid: "Q14802", label: "striped bass" },
  { qid: "Q14803", label: "white bass" },
  { qid: "Q14804", label: "peacock bass" },
  { qid: "Q27167", label: "pike", aliases: ["northern pike"] },
  { qid: "Q14806", label: "muskellunge", aliases: ["muskie"] },
  { qid: "Q14807", label: "pickerel" },
  { qid: "Q14808", label: "walleye" },
  { qid: "Q14809", label: "perch", aliases: ["yellow perch"] },
  { qid: "Q14810", label: "zander" },
  { qid: "Q14811", label: "crappie" },
  { qid: "Q14812", label: "bluegill" },
  { qid: "Q14813", label: "sunfish" },
  { qid: "Q14814", label: "pumpkinseed" },
  { qid: "Q185164", label: "piranha" },
  { qid: "Q14815", label: "pacu" },
  { qid: "Q14816", label: "tetra" },
  { qid: "Q14817", label: "hatchetfish" },
  { qid: "Q14818", label: "pencilfish" },
  { qid: "Q128685", label: "eel", aliases: ["european eel"] },
  { qid: "Q14819", label: "american eel" },
  { qid: "Q14820", label: "moray eel" },
  { qid: "Q14821", label: "conger eel" },
  { qid: "Q14822", label: "electric eel" },
  { qid: "Q14823", label: "arowana" },
  { qid: "Q14824", label: "arapaima", aliases: ["pirarucu"] },
  { qid: "Q14825", label: "gar", aliases: ["alligator gar"] },
  { qid: "Q14826", label: "bowfin" },
  { qid: "Q14827", label: "sturgeon" },
  { qid: "Q14828", label: "beluga sturgeon" },
  { qid: "Q14829", label: "paddlefish" },
  { qid: "Q14830", label: "lungfish" },
  { qid: "Q52866", label: "guppy" },
  { qid: "Q14831", label: "molly" },
  { qid: "Q14832", label: "swordtail" },
  { qid: "Q14833", label: "platy" },
  { qid: "Q14840", label: "angelfish" },
  { qid: "Q14841", label: "discus" },
  { qid: "Q14842", label: "oscar" },
  { qid: "Q14843", label: "tilapia" },
  { qid: "Q14844", label: "cichlid" },
  { qid: "Q14845", label: "betta", aliases: ["siamese fighting fish"] },
  { qid: "Q14846", label: "gourami" },
  { qid: "Q14847", label: "paradise fish" },
  { qid: "Q14848", label: "snakehead" },
  { qid: "Q14849", label: "climbing perch" },

  // ═══════════════════════════════════════════════════════════════════
  // FISH — Bony Fish (Saltwater)
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q21137", label: "tuna", aliases: ["bluefin tuna"] },
  { qid: "Q14851", label: "yellowfin tuna" },
  { qid: "Q14852", label: "albacore" },
  { qid: "Q14853", label: "skipjack tuna" },
  { qid: "Q14854", label: "bigeye tuna" },
  { qid: "Q228053", label: "cod", aliases: ["atlantic cod"] },
  { qid: "Q14856", label: "haddock" },
  { qid: "Q14857", label: "pollock" },
  { qid: "Q14858", label: "whiting" },
  { qid: "Q301052", label: "swordfish" },
  { qid: "Q14859", label: "marlin" },
  { qid: "Q14860", label: "sailfish" },
  { qid: "Q14861", label: "mahi-mahi", aliases: ["dorado", "dolphinfish"] },
  { qid: "Q14862", label: "wahoo" },
  { qid: "Q28001", label: "barracuda" },
  { qid: "Q14863", label: "grouper" },
  { qid: "Q14864", label: "snapper" },
  { qid: "Q14865", label: "mackerel" },
  { qid: "Q14866", label: "king mackerel" },
  { qid: "Q14867", label: "spanish mackerel" },
  { qid: "Q14868", label: "amberjack" },
  { qid: "Q14869", label: "jack" },
  { qid: "Q14870", label: "pompano" },
  { qid: "Q14871", label: "permit" },
  { qid: "Q14872", label: "bonefish" },
  { qid: "Q14873", label: "tarpon" },
  { qid: "Q14874", label: "milkfish" },
  { qid: "Q14875", label: "herring" },
  { qid: "Q14876", label: "sardine" },
  { qid: "Q14877", label: "anchovy" },
  { qid: "Q14878", label: "menhaden" },
  { qid: "Q14879", label: "mullet" },
  { qid: "Q14880", label: "flounder" },
  { qid: "Q14881", label: "halibut" },
  { qid: "Q14882", label: "sole" },
  { qid: "Q14883", label: "plaice" },
  { qid: "Q14884", label: "turbot" },
  { qid: "Q14885", label: "monkfish", aliases: ["anglerfish"] },
  { qid: "Q14886", label: "redfish", aliases: ["ocean perch"] },
  { qid: "Q14887", label: "rockfish" },
  { qid: "Q14888", label: "lionfish" },
  { qid: "Q14889", label: "scorpionfish" },
  { qid: "Q14890", label: "stonefish" },
  { qid: "Q14891", label: "triggerfish" },
  { qid: "Q14892", label: "boxfish" },
  { qid: "Q14893", label: "pufferfish", aliases: ["blowfish"] },
  { qid: "Q14894", label: "porcupinefish" },
  { qid: "Q14895", label: "ocean sunfish", aliases: ["mola mola"] },
  { qid: "Q14896", label: "surgeonfish" },
  { qid: "Q14897", label: "tang" },
  { qid: "Q14898", label: "parrotfish" },
  { qid: "Q14899", label: "wrasse" },
  { qid: "Q14900", label: "damselfish" },
  { qid: "Q33228", label: "clownfish", aliases: ["anemonefish"] },
  { qid: "Q14901", label: "butterflyfish" },
  { qid: "Q14903", label: "rabbitfish" },
  { qid: "Q14904", label: "goatfish" },
  { qid: "Q131177", label: "seahorse" },
  { qid: "Q14905", label: "pipefish" },
  { qid: "Q14906", label: "seadragon" },
  { qid: "Q14907", label: "flying fish" },
  { qid: "Q14908", label: "needlefish" },
  { qid: "Q14909", label: "halfbeak" },
  { qid: "Q14910", label: "squirrelfish" },
  { qid: "Q14911", label: "bigeye" },
  { qid: "Q14912", label: "lanternfish" },
  { qid: "Q14913", label: "dragonfish" },
  { qid: "Q14914", label: "viperfish" },
  { qid: "Q14915", label: "anglerfish", aliases: ["deep sea anglerfish"] },
  { qid: "Q14916", label: "flashlight fish" },
  { qid: "Q14917", label: "frogfish" },
  { qid: "Q14918", label: "batfish" },
  { qid: "Q14919", label: "coelacanth" },

  // ═══════════════════════════════════════════════════════════════════
  // INVERTEBRATES — Insects
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q28319", label: "butterfly", aliases: ["monarch butterfly"] },
  { qid: "Q20928", label: "swallowtail butterfly" },
  { qid: "Q20929", label: "painted lady" },
  { qid: "Q20930", label: "red admiral" },
  { qid: "Q20931", label: "blue morpho", aliases: ["morpho butterfly"] },
  { qid: "Q20932", label: "cabbage white" },
  { qid: "Q131820", label: "moth" },
  { qid: "Q20933", label: "luna moth" },
  { qid: "Q20934", label: "atlas moth" },
  { qid: "Q20935", label: "hawk moth", aliases: ["sphinx moth"] },
  { qid: "Q20936", label: "cecropia moth" },
  { qid: "Q20937", label: "polyphemus moth" },
  { qid: "Q20938", label: "gypsy moth" },
  { qid: "Q20939", label: "silkworm moth" },
  { qid: "Q33976", label: "caterpillar" },
  { qid: "Q102857", label: "bee", aliases: ["honey bee", "honeybee"] },
  { qid: "Q20940", label: "bumblebee" },
  { qid: "Q20941", label: "carpenter bee" },
  { qid: "Q20942", label: "mason bee" },
  { qid: "Q20943", label: "leafcutter bee" },
  { qid: "Q20944", label: "sweat bee" },
  { qid: "Q20945", label: "wasp" },
  { qid: "Q20946", label: "yellowjacket" },
  { qid: "Q20947", label: "hornet" },
  { qid: "Q20948", label: "paper wasp" },
  { qid: "Q20949", label: "mud dauber" },
  { qid: "Q7386", label: "ant" },
  { qid: "Q20951", label: "carpenter ant" },
  { qid: "Q20952", label: "fire ant" },
  { qid: "Q20953", label: "army ant" },
  { qid: "Q20954", label: "leafcutter ant" },
  { qid: "Q20955", label: "bullet ant" },
  { qid: "Q20956", label: "weaver ant" },
  { qid: "Q19088", label: "termite" },
  { qid: "Q25325", label: "beetle" },
  { qid: "Q20958", label: "dung beetle" },
  { qid: "Q20959", label: "rhinoceros beetle" },
  { qid: "Q20960", label: "hercules beetle" },
  { qid: "Q20961", label: "stag beetle" },
  { qid: "Q20962", label: "jewel beetle" },
  { qid: "Q20963", label: "click beetle" },
  { qid: "Q20964", label: "firefly", aliases: ["lightning bug"] },
  { qid: "Q20965", label: "bombardier beetle" },
  { qid: "Q20966", label: "tiger beetle" },
  { qid: "Q20967", label: "ground beetle" },
  { qid: "Q20968", label: "rove beetle" },
  { qid: "Q20969", label: "longhorn beetle" },
  { qid: "Q20970", label: "leaf beetle" },
  { qid: "Q20971", label: "weevil" },
  { qid: "Q11227", label: "ladybug", aliases: ["ladybird"] },
  { qid: "Q20972", label: "asian lady beetle" },
  { qid: "Q39884", label: "dragonfly" },
  { qid: "Q20973", label: "damselfly" },
  { qid: "Q20974", label: "mayfly" },
  { qid: "Q20975", label: "stonefly" },
  { qid: "Q20976", label: "caddisfly" },
  { qid: "Q20977", label: "alderfly" },
  { qid: "Q20978", label: "dobsonfly" },
  { qid: "Q20979", label: "lacewing" },
  { qid: "Q20980", label: "antlion" },
  { qid: "Q20981", label: "scorpionfly" },
  { qid: "Q83976", label: "grasshopper" },
  { qid: "Q20982", label: "locust" },
  { qid: "Q47328", label: "cricket" },
  { qid: "Q20983", label: "mole cricket" },
  { qid: "Q20984", label: "katydid" },
  { qid: "Q20985", label: "cicada" },
  { qid: "Q20986", label: "leafhopper" },
  { qid: "Q20987", label: "planthopper" },
  { qid: "Q20988", label: "treehopper" },
  { qid: "Q20989", label: "aphid" },
  { qid: "Q20990", label: "scale insect" },
  { qid: "Q20991", label: "mealybug" },
  { qid: "Q20992", label: "whitefly" },
  { qid: "Q20993", label: "psyllid" },
  { qid: "Q26745", label: "cockroach" },
  { qid: "Q30126", label: "praying mantis", aliases: ["mantis"] },
  { qid: "Q174795", label: "stick insect", aliases: ["walking stick"] },
  { qid: "Q20995", label: "leaf insect" },
  { qid: "Q20996", label: "earwig" },
  { qid: "Q859312", label: "fly", aliases: ["housefly"] },
  { qid: "Q20997", label: "blow fly" },
  { qid: "Q20998", label: "fruit fly" },
  { qid: "Q20999", label: "tsetse fly" },
  { qid: "Q21000", label: "horse fly" },
  { qid: "Q21001", label: "deer fly" },
  { qid: "Q21002", label: "robber fly" },
  { qid: "Q21003", label: "hoverfly" },
  { qid: "Q21004", label: "bee fly" },
  { qid: "Q21005", label: "crane fly" },
  { qid: "Q30144", label: "mosquito" },
  { qid: "Q21006", label: "midge" },
  { qid: "Q21007", label: "black fly" },
  { qid: "Q21008", label: "sandfly" },
  { qid: "Q27318", label: "flea" },
  { qid: "Q21009", label: "louse" },
  { qid: "Q21010", label: "bed bug" },
  { qid: "Q21011", label: "kissing bug", aliases: ["assassin bug"] },
  { qid: "Q21012", label: "stink bug" },
  { qid: "Q21013", label: "shield bug" },
  { qid: "Q21014", label: "water strider" },
  { qid: "Q21015", label: "backswimmer" },
  { qid: "Q21016", label: "water scorpion" },
  { qid: "Q21017", label: "giant water bug" },
  { qid: "Q21018", label: "water boatman" },

  // ═══════════════════════════════════════════════════════════════════
  // INVERTEBRATES — Arachnids & Myriapods
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q1357", label: "spider" },
  { qid: "Q21019", label: "tarantula" },
  { qid: "Q21020", label: "black widow" },
  { qid: "Q21021", label: "brown recluse" },
  { qid: "Q21022", label: "wolf spider" },
  { qid: "Q21023", label: "jumping spider" },
  { qid: "Q21024", label: "orb-weaver" },
  { qid: "Q21025", label: "golden silk orb-weaver" },
  { qid: "Q21026", label: "garden spider" },
  { qid: "Q21027", label: "crab spider" },
  { qid: "Q21028", label: "fishing spider" },
  { qid: "Q21029", label: "trapdoor spider" },
  { qid: "Q21030", label: "funnel-web spider" },
  { qid: "Q21031", label: "redback spider" },
  { qid: "Q21032", label: "huntsman spider" },
  { qid: "Q19125", label: "scorpion" },
  { qid: "Q21033", label: "emperor scorpion" },
  { qid: "Q21034", label: "deathstalker" },
  { qid: "Q21035", label: "bark scorpion" },
  { qid: "Q21036", label: "whip scorpion", aliases: ["vinegaroon"] },
  { qid: "Q21037", label: "tailless whip scorpion" },
  { qid: "Q21038", label: "camel spider", aliases: ["sun spider", "solifugid"] },
  { qid: "Q21039", label: "daddy longlegs", aliases: ["harvestman"] },
  { qid: "Q8441", label: "tick" },
  { qid: "Q21040", label: "mite" },
  { qid: "Q21041", label: "chigger" },
  { qid: "Q170924", label: "centipede" },
  { qid: "Q21042", label: "giant centipede" },
  { qid: "Q25848", label: "millipede" },
  { qid: "Q21043", label: "giant millipede" },

  // ═══════════════════════════════════════════════════════════════════
  // INVERTEBRATES — Crustaceans
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q4610", label: "crab" },
  { qid: "Q21044", label: "blue crab" },
  { qid: "Q21045", label: "king crab" },
  { qid: "Q21046", label: "snow crab" },
  { qid: "Q21047", label: "dungeness crab" },
  { qid: "Q21048", label: "fiddler crab" },
  { qid: "Q21049", label: "coconut crab" },
  { qid: "Q21050", label: "hermit crab" },
  { qid: "Q21051", label: "horseshoe crab" },
  { qid: "Q122991", label: "lobster", aliases: ["american lobster"] },
  { qid: "Q21052", label: "spiny lobster" },
  { qid: "Q19586", label: "shrimp" },
  { qid: "Q21053", label: "mantis shrimp" },
  { qid: "Q21054", label: "brine shrimp", aliases: ["sea monkey"] },
  { qid: "Q21055", label: "fairy shrimp" },
  { qid: "Q21056", label: "tadpole shrimp" },
  { qid: "Q21057", label: "clam shrimp" },
  { qid: "Q21058", label: "crayfish", aliases: ["crawfish", "crawdad"] },
  { qid: "Q21059", label: "krill" },
  { qid: "Q21060", label: "copepod" },
  { qid: "Q21061", label: "barnacle" },
  { qid: "Q21062", label: "isopod" },
  { qid: "Q21063", label: "pill bug", aliases: ["roly-poly", "woodlouse"] },
  { qid: "Q21064", label: "giant isopod" },
  { qid: "Q21065", label: "amphipod" },
  { qid: "Q21066", label: "skeleton shrimp" },
  { qid: "Q21067", label: "ostracod" },
  { qid: "Q21068", label: "water flea", aliases: ["daphnia"] },
  { qid: "Q21069", label: "triops" },

  // ═══════════════════════════════════════════════════════════════════
  // INVERTEBRATES — Mollusks
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q40152", label: "octopus" },
  { qid: "Q21070", label: "giant octopus" },
  { qid: "Q21071", label: "blue-ringed octopus" },
  { qid: "Q21072", label: "mimic octopus" },
  { qid: "Q81900", label: "squid" },
  { qid: "Q21073", label: "giant squid" },
  { qid: "Q21074", label: "colossal squid" },
  { qid: "Q21075", label: "vampire squid" },
  { qid: "Q21076", label: "bobtail squid" },
  { qid: "Q21077", label: "cuttlefish" },
  { qid: "Q21078", label: "nautilus" },
  { qid: "Q308841", label: "snail", aliases: ["garden snail"] },
  { qid: "Q21079", label: "roman snail" },
  { qid: "Q21080", label: "giant african snail" },
  { qid: "Q21081", label: "cone snail" },
  { qid: "Q21082", label: "whelk" },
  { qid: "Q21083", label: "conch" },
  { qid: "Q21084", label: "cowrie" },
  { qid: "Q21085", label: "periwinkle" },
  { qid: "Q41145", label: "slug" },
  { qid: "Q21087", label: "sea slug", aliases: ["nudibranch"] },
  { qid: "Q21088", label: "sea hare" },
  { qid: "Q21089", label: "abalone" },
  { qid: "Q21090", label: "limpet" },
  { qid: "Q21091", label: "mussel" },
  { qid: "Q21092", label: "oyster" },
  { qid: "Q21093", label: "clam" },
  { qid: "Q21094", label: "scallop" },
  { qid: "Q21095", label: "cockle" },
  { qid: "Q21096", label: "geoduck" },
  { qid: "Q21097", label: "giant clam" },

  // ═══════════════════════════════════════════════════════════════════
  // INVERTEBRATES — Echinoderms, Cnidarians, Sponges & Others
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q25349", label: "starfish", aliases: ["sea star"] },
  { qid: "Q21098", label: "brittle star" },
  { qid: "Q133337", label: "sea urchin" },
  { qid: "Q21099", label: "sand dollar" },
  { qid: "Q21100", label: "sea cucumber" },
  { qid: "Q21101", label: "feather star", aliases: ["crinoid"] },
  { qid: "Q30258", label: "jellyfish" },
  { qid: "Q21102", label: "box jellyfish" },
  { qid: "Q21103", label: "moon jelly" },
  { qid: "Q21104", label: "lion's mane jellyfish" },
  { qid: "Q21105", label: "portuguese man o' war" },
  { qid: "Q190720", label: "sea anemone" },
  { qid: "Q192814", label: "coral" },
  { qid: "Q21106", label: "brain coral" },
  { qid: "Q21107", label: "staghorn coral" },
  { qid: "Q21108", label: "sea pen" },
  { qid: "Q21109", label: "sea fan", aliases: ["gorgonian"] },
  { qid: "Q21110", label: "hydra" },
  { qid: "Q187034", label: "sponge" },
  { qid: "Q21111", label: "comb jelly" },
  { qid: "Q21112", label: "flatworm", aliases: ["planarian"] },
  { qid: "Q21113", label: "tapeworm" },
  { qid: "Q21114", label: "fluke" },
  { qid: "Q21115", label: "roundworm", aliases: ["nematode"] },
  { qid: "Q21116", label: "rotifer" },
  { qid: "Q21117", label: "tardigrade", aliases: ["water bear"] },
  { qid: "Q21118", label: "velvet worm" },
  { qid: "Q26863", label: "leech" },
  { qid: "Q144550", label: "earthworm", aliases: ["worm"] },
  { qid: "Q21119", label: "ragworm" },
  { qid: "Q21120", label: "lugworm" },
  { qid: "Q21121", label: "tube worm" },
  { qid: "Q21122", label: "bristle worm" },
  { qid: "Q21123", label: "feather duster worm" },
  { qid: "Q21124", label: "bryozoan", aliases: ["moss animal"] },
  { qid: "Q21125", label: "brachiopod", aliases: ["lamp shell"] },
  { qid: "Q21126", label: "tunicate", aliases: ["sea squirt"] },
  { qid: "Q21127", label: "lancelet", aliases: ["amphioxus"] },

  // ═══════════════════════════════════════════════════════════════════
  // EXTINCT ANIMALS
  // ═══════════════════════════════════════════════════════════════════
  { qid: "Q430", label: "dinosaur" },
  { qid: "Q130982", label: "tyrannosaurus", aliases: ["t-rex", "t rex"] },
  { qid: "Q131630", label: "triceratops" },
  { qid: "Q131148", label: "stegosaurus" },
  { qid: "Q131115", label: "brachiosaurus" },
  { qid: "Q18510997", label: "velociraptor" },
  { qid: "Q131138", label: "diplodocus" },
  { qid: "Q13099", label: "spinosaurus" },
  { qid: "Q13129", label: "allosaurus" },
  { qid: "Q13185", label: "ankylosaurus" },
  { qid: "Q13102", label: "parasaurolophus" },
  { qid: "Q13107", label: "iguanodon" },
  { qid: "Q13112", label: "apatosaurus" },
  { qid: "Q13116", label: "brontosaurus" },
  { qid: "Q13120", label: "carnotaurus" },
  { qid: "Q13123", label: "dilophosaurus" },
  { qid: "Q13126", label: "compsognathus" },
  { qid: "Q13130", label: "pachycephalosaurus" },
  { qid: "Q13133", label: "gallimimus" },
  { qid: "Q13136", label: "deinonychus" },
  { qid: "Q13140", label: "microraptor" },
  { qid: "Q13144", label: "oviraptor" },
  { qid: "Q13147", label: "protoceratops" },
  { qid: "Q13150", label: "styracosaurus" },
  { qid: "Q13153", label: "pteranodon" },
  { qid: "Q19627", label: "archaeopteryx" },
  { qid: "Q13156", label: "ichthyosaur" },
  { qid: "Q13159", label: "plesiosaur" },
  { qid: "Q13162", label: "mosasaur" },
  { qid: "Q13165", label: "plesiosaurus" },
  { qid: "Q13168", label: "liopleurodon" },
  { qid: "Q15108", label: "dimetrodon" },
  { qid: "Q26904", label: "mammoth", aliases: ["woolly mammoth"] },
  { qid: "Q19262", label: "mastodon" },
  { qid: "Q18573", label: "saber-toothed tiger", aliases: ["saber toothed tiger", "smilodon"] },
  { qid: "Q13172", label: "glyptodon" },
  { qid: "Q13174", label: "megatherium", aliases: ["giant ground sloth"] },
  { qid: "Q130966", label: "dodo" },
  { qid: "Q48072", label: "passenger pigeon" },
  { qid: "Q21371", label: "tasmanian tiger", aliases: ["thylacine"] },
  { qid: "Q14338", label: "quagga" },
  { qid: "Q17972", label: "moa" },
  { qid: "Q14289", label: "great auk" },
  { qid: "Q18977", label: "stellar's sea cow" },
  { qid: "Q17984", label: "carolina parakeet" },
  { qid: "Q13255", label: "irish elk", aliases: ["giant deer"] },
  { qid: "Q13258", label: "woolly rhinoceros" },
  { qid: "Q13261", label: "cave bear" },
  { qid: "Q13264", label: "cave lion" },
  { qid: "Q13267", label: "short-faced bear" },
  { qid: "Q13270", label: "dire wolf" },
  { qid: "Q13273", label: "aurochs" },
  { qid: "Q13276", label: "terror bird", aliases: ["phorusrhacid"] },
  { qid: "Q13279", label: "megalodon" },
  { qid: "Q13282", label: "dunkleosteus" },
  { qid: "Q13285", label: "trilobite" },
  { qid: "Q13288", label: "ammonite" },
  { qid: "Q13291", label: "helicoprion" },
  { qid: "Q13294", label: "basilosaurus" },
  { qid: "Q13297", label: "dorudon" },
  { qid: "Q13300", label: "andrewsarchus" },
  { qid: "Q13303", label: "indricotherium", aliases: ["paraceratherium"] },
  { qid: "Q13306", label: "chalicothere" },
  { qid: "Q13309", label: "entelodont", aliases: ["hell pig"] },
  { qid: "Q131320", label: "pterodactyl", aliases: ["pterosaur"] },
  { qid: "Q13313", label: "quetzalcoatlus" },
  { qid: "Q13316", label: "elasmotherium", aliases: ["siberian unicorn"] },
  { qid: "Q13319", label: "megalania" },
  { qid: "Q13322", label: "diprotodon" },
  { qid: "Q13325", label: "procoptodon", aliases: ["giant kangaroo"] },
  { qid: "Q13328", label: "haast's eagle" },
  { qid: "Q13331", label: "elephant bird" },
  { qid: "Q13334", label: "baiji", aliases: ["chinese river dolphin"] },
  { qid: "Q13337", label: "golden toad" },
];

// ── Lookup Index ─────────────────────────────────────────────────────

/** Fast lookup map built from the animals array. Key = lowercase name. */
const lookupMap = new Map<string, AnimalEntry>();

function buildLookup(): void {
  if (lookupMap.size > 0) return;
  for (const entry of animals) {
    lookupMap.set(entry.label.toLowerCase(), entry);
    if (entry.aliases) {
      for (const alias of entry.aliases) {
        if (!lookupMap.has(alias.toLowerCase())) {
          lookupMap.set(alias.toLowerCase(), entry);
        }
      }
    }
  }
}

/**
 * Look up an animal name in the local dataset.
 * Returns the AnimalEntry if found (case-insensitive), otherwise undefined.
 */
export function localLookup(
  name: string
): { qid: string } | undefined {
  buildLookup();
  const entry = lookupMap.get(name.toLowerCase().trim());
  if (!entry) return undefined;
  return { qid: entry.qid };
}

/** Return the total number of entries in the local dataset. */
export function datasetSize(): number {
  return animals.length;
}
